### ISSUE TITLE
Data Usage 

### ISSUE THREAD

**Issue by ttshivhula** [shellhub-io/shellhub#102]
This is not an issue this is just a question.

First of all thanks for this great project I love it!!

I just want to know how much data the software will use to keep the a raspberry pi connected to the server. We have a bunch of raspberry pis on the field and we are planning to start using this software. Can someone please give me an estimation of how much data we can expect to use per day to keep the raspberry pi connected to the server.

**Comment by otavio** [comment]
@ttshivhula, we are glad you loved it. We love it as well :-)

This is an interesting aspect we did not consider so we cannot provide you an answer right away, however, we started to look at how we can measure it so we can collect this information.

**Comment by gustavosbarreto** [comment]
According to network traffic generated by Wireshark the total of bytes sent/received by ShellHub in an interval of 60 seconds is 9755/9494, respectively.

We are also looking for a way on how we can decrease the amount of network traffic. We will notify you once any progress is made on this.

**Comment by ttshivhula** [comment]
Thanks, guys for those numbers appreciate it! definitely going to try and see how we can reduce data usage because I live in a world where data is very expensive.

**Comment by otavio** [comment]
@ttshivhula the data is mostly used on the keep-alive messages and ping, for a day it should use about 12mb. Is it too much for your use case?

**Comment by ttshivhula** [comment]
Currently we are using Dataplicity and the data usage is around 3+ mb a day. I don't know how they are doing it. We are just looking to reduce costs that's one of the reasons why shellhub is so great for our business because it's free and open source but if I add the cost of the extra data that is going to be used then the overall cost wil then increase.

**Comment by jwillmer** [comment]
@ttshivhula  We are using Wireguard (VPN) server that all our remote devices connect to. It uses close to 0 bandwidth to keep open. The only issue is that all devices are linked in the same network and if one gets compromised it can access/see all other devices. 

It's not the optimal solution but the only one we could find so far that does not eat up all the bandwidth.
