### ISSUE TITLE
Others icons SO in list devices

### ISSUE THREAD

**Issue by leonardojoao** [shellhub-io/shellhub#116]
I was looking at the list of devices and found that my operating system icon is not showing. 
You should add other icons.

**Comment by otavio** [comment]
We ought to add the icons for:

- [ ] Alpine (font fl-alpine)
- [ ] Arch Linux (font fl-archlinux)
- [ ] CentOS (font fl-centos)
- [ ] CoreOS (font fl-coreos)
- [ ] Debian (font fl-debian)
- [ ] Devuan (font fl-devuan)
- [ ] elementary OS  (font fl-elementary)
- [ ] Fedora (font fl-fedora)
- [ ] FreeBSD    (font fl-freebsd)
- [ ] Gentoo (font fl-gentoo)
- [ ] Linux Mint (font fl-linuxmint)
- [ ] Mageia (font fl-mageia)
- [ ] Manjaro    (font fl-manjaro)
- [ ] Mandriva   (font fl-mandriva)
- [ ] NixOS  (font fl-nixos)
- [ ] OpenSUSE   (font fl-opensuse)
- [ ] Raspberry Pi   (font fl-raspberry-pi)
- [ ] Red Hat    (font fl-redhat)
- [ ] Sabayon    (font fl-sabayon)
- [ ] Slackware  (font fl-slackware)
- [ ] Ubuntu (font fl-ubuntu)
- [ ] Void   (font fl-void)

It should be based on the `os-release` ID for each respective distro.
