### ISSUE TITLE
[feature] Namespace Member Roles

### ISSUE THREAD

**Issue by eduardoveiga** [shellhub-io/shellhub#1203]
Today we had owner that can do anything, including add another members, change settings and delete information
and regular members that can only connect on devices

this issue is about to create some roles to members to define new privileges

**Comment by eduardoveiga** [comment]
Today we had owner that can do anything, including add another members, change settings and delete information 
and regular members that can only connect on devices 

this issue is about to create some roles to members to define new privileges

**Comment by leonardojoao** [comment]
-Migration:
- [ ] Modify namespace; modify the member list to support an object list. Ex: ``[{id: user_id, type: owner|admin|operator|observer}...]``.

-API:
- [ ] Modify the add member in the namespace to support the access type;
- [ ] Add middleware;
- [ ] Can only add/remove down.

-UI:
- [ ] Modify the list to show the access type;
- [ ] Add the user related to the type of access;
- [ ] Block actions according to table

**Comment by gustavosbarreto** [comment]
Implemented in #1400
