### ISSUE TITLE
REST API to get the current shellhub version?

### ISSUE THREAD

**Issue by openedhardware** [shellhub-io/shellhub#1207]
Is there any API that we can get the current shellhub agent version from the server?

If so, could you update (this)[https://docs.shellhub.io/api/] document?

**Comment by gustavosbarreto** [comment]
> Is there any API that we can get the current shellhub agent version from the server?
> 
> If so, could you update (this)[https://docs.shellhub.io/api/] document?

You can check current version running following:

```
curl  https://cloud.shellhub.io/info
```

**Comment by openedhardware** [comment]
Perfect!

**Comment by openedhardware** [comment]
@gustavosbarreto 
Seems the API webpage is dead - https://docs.shellhub.io/api/

Could you check?

**Comment by gustavosbarreto** [comment]
> @gustavosbarreto Seems the API webpage is dead - https://docs.shellhub.io/api/
> 
> Could you check?

https://docs.shellhub.io/developers/openapi
