### ISSUE TITLE
Recovering devices

### ISSUE THREAD

**Issue by lmlmlmlml** [shellhub-io/shellhub#1303]
Hello folks
I have a self hosted shellhub solution, but I, mistakenly, trying to update my shellhub (https://docs.shellhub.io/admin-manual/updating/) followed through the tutorial didn't see  the warning to backup backup MongoDB data before updating mongodb database, since it's on the bottom of the page.

Is there a way to restore previous configurations? devices or environments (tenant)?
Otherwise, can I manually edit the local database adding the tenant_id's I was using (I've got devices deployed, pointing the a given tenant ID, so I suppose I could create same tenant id and the devices would ask for being connected)?

I appreciate any help on the matter. Thanks

**Comment by otavio** [comment]
The upgrade didn't work?

**Comment by lmlmlmlml** [comment]
Yep, the upgrade worked, but one of the upgrade steps is `make upgrade_mongodb`, which I think erased the entries I had.

**Comment by otavio** [comment]
@lmlmlmlml have it worked?
