### ISSUE TITLE
Numered rows, please.

### ISSUE THREAD

**Issue by leoheck** [shellhub-io/shellhub#1325]
Could you please add a column with numbers in front of this thing here?

![image](https://user-images.githubusercontent.com/1277920/135928353-73a59c0b-87d2-4afa-9537-f3ffa6d5f2bd.png)

**Comment by otavio** [comment]
@leoheck, we'd like to understand why you'd like something like this?

**Comment by leoheck** [comment]
I have many devices, and it is good to have a numbered line when we are
communicating, especially if we have teams with members from other
countries. This is an usability improvement. Also, having numbers would be
easy to know how many devices we have in this list.

--
Leandro Heck

**Comment by otavio** [comment]
Usually, people filter the devices using the device id. I think putting a number in front it'll mess up the looking and feel.

**Comment by leoheck** [comment]
A column called #, with 1, 2, 3, 4, 5, .. N is not going to mess with the look and feel.

**Comment by otavio** [comment]
@leoheck patches are welcome. We're focused on other things at this moment but if you provide a patch and the end result looks great, it can be reviewed and discussed.

**Comment by leoheck** [comment]
Sorry. I am just an user that didn't like tbe way devices are being displayed without having a number in front of those lines. But if you guys don't need any possible indication of order and quantity it is fine for me. I won't use it anyway. Thanks dude.
