### ISSUE TITLE
Terminal icon next to remove icon.

### ISSUE THREAD

**Issue by leoheck** [shellhub-io/shellhub#1327]
Not a good job here.

**Comment by leonardojoao** [comment]
Hello dear @leoheck,
Thanks for your comment. But, can you explain more about what you think is "not a good job"?

Thus, we can assess what needs to be improved in the work developed.

**Comment by otavio** [comment]
@leoheck please check new 0.8.2 release. We did some minor improvements on the UX.

**Comment by leoheck** [comment]
Not sure what was the improvement. But this looks still the same
![image](https://user-images.githubusercontent.com/1277920/147017594-abd74e00-763e-4d01-8254-bec12b09c6c6.png)

The next idea of improvement would be a button to format the computer, next to the button to favorite the entry, next button to nuke the whole world. 

![image](https://user-images.githubusercontent.com/1277920/147018300-439cc0fa-5ef8-4faa-acdb-0e3aa03d7796.png)

Be my guest when trying to add an entry to favorites on a weekend when the whole thing is catching fire and your client is crazy yelling at you. Hope the world continues to exist by Monday. =)

**Comment by otavio** [comment]
It has changed. As an example:
![image](https://user-images.githubusercontent.com/25278/147090711-a4afda83-bbbf-46de-91e5-74101940c20c.png)

**Comment by leoheck** [comment]
How is this a change?

There is still the most used button (to connect the device) pretty close to
the delete the entry.

The Connect button could be visible, and then the Delete button could be
hidden inside the 3 dots menu, or something.

Or It may could help a bit if the Delete button asks for a confirmation or
something, but I didn't try to remove an entry yet.

**Comment by gustavosbarreto** [comment]
> How is this a change?

I think this is a UX improvement since we are following material design principles.

> There is still the most used button (to connect the device) pretty close to the delete the entry.

Maybe a horizontal line between "most used buttons" and other items can help you.

> Or It may could help a bit if the Delete button asks for a confirmation or
something, but I didn't try to remove an entry yet.

Please do that before complain about this.

**Comment by gustavosbarreto** [comment]
> The next idea of improvement would be a button to format the computer, next to the button to favorite the entry, next button to nuke the whole world.

@leoheck The next ideia would be a button to read our [CODE OF CONDUCT](https://github.com/shellhub-io/shellhub/blob/master/CODE_OF_CONDUCT.md).

**Comment by leoheck** [comment]
that would be awesome.
