### ISSUE TITLE
error in manual compiled agent

### ISSUE THREAD

**Issue by MartinKuhl** [shellhub-io/shellhub#1462]
I manual compiled the agent in version 0.8.1 and tried to connect the agent with the local shellhub server:

(used go version go1.17.3 linux/amd64)

`root@6d7c79bea057:/var/www/html# SERVER_ADDRESS=192.167.177.130 PRIVATE_KEY=/etc/shellhub.key TENANT_ID=xxxxxxxx ./agent`

just after I entered the command I get the following error message:
![image](https://user-images.githubusercontent.com/55736453/143275398-12e94468-7da6-444a-afbb-d5df1cc98dc9.png)

As a background information: I will use the agent inside a docker container.

Any ideas?

**Comment by gustavosbarreto** [comment]
`SERVER_ADDRESS` must have protocol scheme (`http` or `https`).

For example:

```console
SERVER_ADDRESS=http://192.167.177.130
```

**Comment by MartinKuhl** [comment]
oh yes of cause that:s was my fault.
Thanks a lot
