### ISSUE TITLE
There is something wired with the Devices List using the API

### ISSUE THREAD

**Issue by leoheck** [shellhub-io/shellhub#1519]
I am trying to get this list (commands from API document version 1.0.0)

Shellhub shows 11 devices on my development namespace (see the picture below). It also shows 2 devices online (see the second picture below).

But when I use the API I get just 1 device. which is online but the status is "pending". This device is not the 2 that the Shellhub page shows as online. It is one of those that are on the pending list. 

What is going on here? How stable is this API 1.0.0? Am I doing something wrong?
 
![image](https://user-images.githubusercontent.com/1277920/145334904-1a2e4235-3239-4abe-a169-9d11c857550f.png)

![image](https://user-images.githubusercontent.com/1277920/145334153-5495ee05-6388-4967-8f92-da2fc8aa3bef.png)

**Comment by leoheck** [comment]
What is the definition of Devices and Sessions? The data I am getting is pretty strange for me to understand these terms.
For instance, looking at the json for the list of the devices. I am seeing a list with 3 items, and they are all the same device.

**Comment by henrybarreto** [comment]
Hi, Leo.

How do you mount your URI? I mean the parameters you are using.

**Comment by gustavosbarreto** [comment]
> What is going on here? How stable is this API 1.0.0? Am I doing something wrong?

Probably yes. The frontend is using the same API/endpoints that are described in the OpenAPI spec.

Can you please provide details on the complete request you send?
