### ISSUE TITLE
 [feature] support Public Key Authentication

### ISSUE THREAD

**Issue by shawn111** [shellhub-io/shellhub#157]
I like shellhub user interface and the design.
Could you add support Public Key Authentication?

Thank you.

**Comment by otavio** [comment]
Thank you for reporting this issue; we intend to add support for key authentication in future but for now we are focusing on more basic stuff and polishing the code base.

**Comment by jwillmer** [comment]
Can we already use pub key auth with 3d party clients like putty? Is this just a website limitation?

**Comment by otavio** [comment]
Not yet. We are still working on more basic functionality.

**Comment by AntoinedeChassey** [comment]
This functionality is a must have 😇
Hope to see this coming!

**Comment by shawn111** [comment]
@otavio if we store the public key on the web site, let users manage their keys like keys on github.
It could avoid keys store on the agent container and avoid agent container to access hosts files.

**Comment by otavio** [comment]
@shawn111 good idea :-D thanks for sharing it.

**Comment by gustavosbarreto** [comment]
Hello @shawn111 @jwillmer @AntoinedeChassey , the feature will be available in next release. Thanks for your patience.

**Comment by nejeoui** [comment]
Great project folks!
Hope to see ssh key authentication added soon, it is a must have functionality
