### ISSUE TITLE
Quick connect button

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#1574]
The quick connect button makes connecting to devices effortless.

After clicking on _New Connection_ button a dialog appears showing a list of:
* Favorite devices
* Recent devices
* A search field for device list

It would be nice to have a keyboard shortcut for the dialog (like discord Quick Switcher)

### Mockup

![screencapture-localhost-2021-12-21-20_15_02](https://user-images.githubusercontent.com/86747/147010569-24c283f5-39f8-4089-ba28-c1652c48095d.png)

**Comment by MadhuMPandurangi** [comment]
Hi @gustavosbarreto, I'm interested to work on this issue. Can u please assign this to me

**Comment by otavio** [comment]
@MadhuMPandurangi we've merged the new UI in `master` and it'd be nice if you could use this for the work.
