### ISSUE TITLE
api: remove hard coded jwt authentication secret

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#16]
Right now the JWT authentication secret is hard coded into the code (see links below):

https://github.com/shellhub-io/shellhub/blob/ee6d67a609310611a05f0639dd6c939c63cfc2f2/api/main.go#L443

https://github.com/shellhub-io/shellhub/blob/ee6d67a609310611a05f0639dd6c939c63cfc2f2/api/main.go#L466

Task: use an environment variable to get the JWT secret value replacing the hard coded value

**Comment by u5surf** [comment]
@gustavosbarreto 
Hi, I’ll take this up, however I‘m not sure it’s good that it only converts all to `os.Getenv`.  for example I don’t know which the tests of this package is used them. CI may be getting fail when it changes which doesn’t care environment variables.
