### ISSUE TITLE
nsenter: cannot open /host//home/torizon: No such file or directory

### ISSUE THREAD

**Issue by microhobby** [shellhub-io/shellhub#161]
Steps to reproduce:
1- Toradex Apalis iMX6 with Ixora carrier board;
2- Torizon installed on module;
3- Follow the [one line installation script (Docker)](http://docs.shellhub.io/guides/registering-device/) and execute the line on the board;
4- Try to access the ssh using the shellhub sshid;

Result:
```
nsenter: cannot open /host//home/torizon: No such file or directory
Connection to cloud.shellhub.io closed by remote host.
Connection to cloud.shellhub.io closed.
```

Expected result: access to the board terminal successfully

## Additional Information

Torizon `/home` is a symlink to `var/rootdirs/home`. If I try to change the `/etc/passwd` with the full path the result is the same (but now with the full path):
```
nsenter: cannot open /host//var/rootdirs/home/torizon: No such file or directory
Connection to cloud.shellhub.io closed by remote host.
Connection to cloud.shellhub.io closed.
``` 

The only way it worked (workaround) was leaving the path empty in `/etc/passwd`:
```
torizon:x:1000:1000:::/bin/sh
```

**Comment by gustavosbarreto** [comment]
Docker volumes does not follow symlinks inside containers. There are a big challenge for us to cover your use case. Maybe the one-line install script does not fit for you. In your case you can mount both directories changing the `docker run` command from one-line install script.

I could modify the one-line install script but it is impossible to predict which users are using a symlink to their home directory.

In Torizon, are all user directories a symlink to the same directory?

**Comment by microhobby** [comment]
@gustavosbarreto thanks for the return. I checked here `/var/rootdirs/home/torizon` is also a symlink putting the full path `/sysroot/home/torizon` on the `/etc/passwd` works.

**Comment by gustavosbarreto** [comment]
@microhobby Can you test it again? I think it has been fixed

**Comment by otavio** [comment]
It has been two weeks without a response. We'll be closing this for now.

In case it does not work for you @microhobby please let us know.

**Comment by microhobby** [comment]
@otavio and @gustavosbarreto sorry for the delay in the report.

I tested it and yes everything is working without needing any workaround, I just ran the one line installation script and that is it, I was able to access it via the ShellHub cloud and my local SSH client.

Is there a commit with a solution? I got curious.

Anyway thanks for working on it.

**Comment by otavio** [comment]
Honestly, it was fixed with a refactor @gustavosbarreto did in the code. So the exact commit that fixed it I am not sure. Maybe @gustavosbarreto knows it.
