### ISSUE TITLE
Shellhub crash/Hang due to storage full: Returning "The request has failed, please try again"

### ISSUE THREAD

**Issue by venugopalreddysomu** [shellhub-io/shellhub#1611]
Hi,
     i have installed shell hub community edition on AWS small ubuntu server, it was working fine, after a month time, the storage 17GB was full, i think it was due to session loggings.

Issue:
when the storage 17GB was full, the main login page also did not open, i have increased storage to 60GB, then the login page came but it was showing the below error "The request has failed, please try again". can someone help in solving the issue?

I have around 40 devices created with this setup and they deployed in the field. please help me to fix the issue.

![image](https://user-images.githubusercontent.com/51040807/148723466-ad65a956-9ea9-4d84-a9e6-ce128f719a38.png)

Deployed version:  0.7.5

**Comment by otavio** [comment]
@venugopalreddysomu, we need to understand what is happening as ShellHub, especially in the Community / Open Source, uses minimal disk space.

Could you upgrade your version to 0.8.2 and see if it helps?

**Comment by otavio** [comment]
Please check if 0.8.2 helps, otherwise we can try to take a look.

**Comment by andy-freund** [comment]
@otavio I made the upgrade to 0.8.2, but the error message is still the same.

**Comment by otavio** [comment]
@andy-freund, problem solved. It was MongoDB which that was corrupted. See https://docs.mongodb.com/manual/tutorial/recover-data-following-unexpected-shutdown/

**Comment by gustavosbarreto** [comment]
@venugopalreddysomu I think you have the same problem as @andy-freund.
I'm closing this issue.

**Comment by andy-freund** [comment]
@otavio Great, it works now. Thank you very much.
