### ISSUE TITLE
Shellhub installation crash

### ISSUE THREAD

**Issue by PrzemekSkw** [shellhub-io/shellhub#1667]
Hello, I try to install shellhub on my Ubuntu Server 20.04 (Raspberrypi3) where I have installed Docstarter (easy docker installer). Installed apps: Organizr, Qbittorrent, Heimdall, Watchtower.
I connect to my server with VPN wireguard tunnel.

I install Shellhub with instructions from website like: `make keygen` and `make start`.
At the end I noticed that errors and now cannot connect to my server.
```
Creating shellhub_ssh_1   ... error
WARNING: Host is already in use by another container

ERROR: for shellhub_ssh_1  Cannot start service ssh: driver failed programming external connectivity on endpoint shellhub_ssh_1 (229a3b9fe521f1c59df7f7d3fa9013022b3e1125070f824ff842fc4469825abe): Error starting userlCreating shellhub_mongo_1 ... done
```
How to fix that?
Regards.

**Comment by gustavosbarreto** [comment]
Something is already running on port 22 which shellhub is trying to bind to.

Check `netstat -tulpen and stop the application bound to port 22 or change the ShellHub default SSH port.

**Comment by PrzemekSkw** [comment]
Hi, thanks for answer. I use port 22 to connect ssh to my server. How to change Shellhub default port before installation?
Regards,
Przemek

**Comment by gustavosbarreto** [comment]
> Hi, thanks for answer. I use port 22 to connect ssh to my server. How to change Shellhub default port before installation? Regards, Przemek

https://docs.shellhub.io/admin-manual/configuring/#shellhub_ssh_port

**Comment by PrzemekSkw** [comment]
Thanks but is there a installation guide, maybe with docker-compose?

**Comment by gustavosbarreto** [comment]
> Thanks but is there a installation guide, maybe with docker-compose?

https://docs.shellhub.io/getting-started/installing/

**Comment by PrzemekSkw** [comment]
> > Thanks but is there a installation guide, maybe with docker-compose?
> 
> https://docs.shellhub.io/getting-started/installing/

I install with that link and it install default port 22 and crash my system.
Regards.
