### ISSUE TITLE
Raspian 64bit (Debian bulleseye) with v0.9.0 -> Remote Connection: Permission denied

### ISSUE THREAD

**Issue by andy-freund** [shellhub-io/shellhub#1694]
Today I put a Raspberry Pi with the latest Raspian 64bit image into operation and installed Shellhub under v0.9.0 on it.
When connecting, I get a "Permission Denied" message. All other RPi with the 32bit OS work.

**Comment by andy-freund** [comment]
> > Today I put a Raspberry Pi with the latest Raspian 64bit image into operation and installed Shellhub under v0.9.0 on it. When connecting, I get a "Permission Denied" message. All other RPi with the 32bit OS work.
> 
> @andy-freund The raspbian version of both 32bits and 64bits machines are the same?

I use 32bit Raspian 10 (buster) and 11 (bullseye). Both are working well.
But 64bit Raspian 11 (bullseye) will not work ...

**Comment by andy-freund** [comment]
Problem is solved:

rbi-update 
-> Update from  5.10.92-v8+ to 5.15.21-v8+

Now it works.

sorry to disturb you

**Comment by gustavosbarreto** [comment]
> sorry to disturb you

np

**Comment by nilnullzip** [comment]
Really great project here. I signed up at ShellHub and I am encountering this same issue. I am using the latest Raspberry Pi OS:

```
Linux raspberrypi 5.10.103-v7l+ #1530 SMP Tue Mar 8 13:05:01 GMT 2022 armv7l GNU/Linux
```

Unfortunately `rpi-update` is not a desirable solution; see warning below. Any ideas?

"rpi-update is a command line application that will update your Raspberry Pi OS kernel and VideoCore firmware to the latest pre-release versions.

WARNING | Pre-release versions of software are not guaranteed to work. You should not use rpi-update on any system unless recommended to do so by a Raspberry Pi engineer. It may leave your system unreliable or even completely broken. It should not be used as part of any regular update process."

**Comment by otavio** [comment]
@nilnullzip glad you like the project. Unfortunately, being an issue in Raspberry Pi OS, you are in a complicated problem; I suggest you try a new version and see if it works for you.
