### ISSUE TITLE
Cannot create first user

### ISSUE THREAD

**Issue by glynhudson** [shellhub-io/shellhub#1763]
I've fired up a new shellhub instance running the latest version v0.9.1-rc.2.

Everything starts fine and I can access the UI, however I can't seem to create the first user

`./bin/add-user <username> <password> <email>`

returns 

```
Error: failed to create a new user
Usage:
  cli add-user [flags]

Flags:
  -h, --help   help for add-user

ERRO[0030] failed to create a new user 
```

Any idea what's causing the issue?

**Comment by gustavosbarreto** [comment]
> I've fired up a new shellhub instance running the latest version v0.9.1-rc.2.

A release candidate (rc) version indicates that the version is unstable and might are not meant for production. You can use the latest stable version (v0.9.0) or wait for the next stable release. (v0.9.1) if you want. 

We don’t support release candidate versions. When you have installing a release candidate version you should be aware that release candidates are not meant for production and the risks associated with them.

@glynhudson  Please reopen this issue if you ever encounter this error again using a stable release.

**Comment by glynhudson** [comment]
Apologies, I mistakenly cloned the shellhub repo without specifying `-b v0.9.0`. 

I can confirm this issue does not affect v0.9.0 👍 

Sorry for the hassle

**Comment by otavio** [comment]
@glynhudson thanks for reporting it anyway. Once we make the v0.9.1 please give it a go!
