### ISSUE TITLE
Cannot connect to old devices after upgrade & server migration

### ISSUE THREAD

**Issue by glynhudson** [shellhub-io/shellhub#1770]
I've upgraded from v0.3.7 (old server) to v0.9.0 (new server), I've successfully migrated the database and moved the DNS using the same domain name. I can successfully add new and access new devices and see all my old devices listed as online. However, I cannot connect to any of the older devices, the terminal just hangs. 
 
Do I need to upgrade the client running on all my old devices to be compatible with v0.9.0? I would need to move the DNS back to my old server running v0.3.7 to regain access to them.

**Comment by otavio** [comment]
The agents are intended to succeed to connect. It might be a bug.

What is the message you see when trying to connect to them?

**Comment by glynhudson** [comment]
No message, just a blank terminal. Is there a way I can access debug logs?

**Comment by glynhudson** [comment]
I'm getting the error 

```
ssh_1        | time="2022-03-17T00:57:32Z" level=info msg="Handling session request" session=xxxxxxxx1d425367737a11b13d39527ecedaeb285fbafe5fba target=pi@xxxxxxxxxb443e041b9fd4e565e5e862907485af0d1c
ssh_1        | time="2022-03-17T00:57:32Z" level=error msg="Failed to dial to tunnel" err="revdial.Dialer closed" session=xxxxxxxxx2bb21d425367737a11b13d39527ecedaeb285fbafe5fba
```

**Comment by noreng-jg** [comment]
Hello @glynhudson 

Since `v0.3.0` the agent has a self-updating daily pooling mechanism, so it wouldn't be required to delete and recreate it. It appears that it doesn't attempt an update during connection, though.

Would you also have the logs for the previous agent container v0.3.7, when
this issue occurred? You might have to install it again by using the old script, check the blank terminal happens to appear again, then run something like:

```bash
docker logs $(docker ps -a | grep agent:v0.3.7 | awk '{ print $1 }' | head -n 1)
```

This could be a past issue that'd been fixed for the newest versions of the agent.

**Comment by glynhudson** [comment]
>Since v0.3.0 the agent has a self-updating daily pooling mechanism

Interesting, does the agent self-update based on the version of the shellhub server? I've not actually left the DNS set to the new server for more than a few hours. Do you think if I leave the DNS pointing to the new server running the latest version of shellhub for 24hrs the agents will self-update? At what time does the update take place? 

I've recreated the `v0.3.7` agent, and tried to connect to it from a v0.9.0 server, as before I get a blank terminal. However, `docker logs shellhub ` doesn't return any logs from the agent

**Comment by otavio** [comment]
@glynhudson, yes, it does. It uses the `/info` route as the source of information. So we'd expect it to update itself to the newer release automatically; however, we do not understand why you cannot connect to the device since we didn't reproduce this failure here.

**Comment by glynhudson** [comment]
Interesting, is there a way I could trigger this update manually? 

FYI this is my `.env.override` on the new server 

```
SHELLHUB_SSH_PORT=44
SHELLHUB_AUTO_SSL=true
SHELLHUB_REDIRECT_TO_HTTPS=true
SHELLHUB_DOMAIN=domain.com
```

The new server is terminating SSL in the docker container, while the old server used an ngix proxy front end for SSL termination. Both servers use CloudFlare DNS proxy.  

Happy to provide more information over DM.

**Comment by otavio** [comment]
You can't trigger the update manually. It runs daily, automatically. 

The old releases had almost no logging in the agent (a thing we fixed in new releases). We tried to reproduce it here using:

- old agent (0.3.7) and new server (0.9.0)
- new agent (0.9.0) and new server (0.9.0)

In both cases, it runs fine. One thing you mentioned in the last comment bothers me:

> The new server is terminating SSL in the docker container, while the old server used an ngix proxy front end for SSL termination.

It might be a valid test to avoid those changes and reduce the setup delta between the old and new server so it might raise some clue about the culprit

**Comment by glynhudson** [comment]
The new server works fine with the new agent. What time of day does the update take place? After the update, will the agent show the new version of the container name returned by `docker ps`? So I can check if the update has taken place. 

I did initially to upgrade the shellhub server in place on the old server (0.3.7 > 0.9.0), however I ran into the issue of not being able to update the database, as reported https://gitter.im/shellhub-io/community?at=62281c2e6b9124232025a54b

`make upgrade_mongodb`

returns

`sh: 1: Syntax error: end of file unexpected make: *** [upgrade_mongodb] Error 2`

I figured the issue was caused by the old server is running very old packages (ubuntu 14.04). 

Would it be useful if I gave you a login via to help with debugging? I'm happy to pay for your time. This is a production system, I'm keen to minimise downtime. Thanks a lot for your help.

**Comment by otavio** [comment]
I'll ask our business people to contact you.

**Comment by glynhudson** [comment]
To follow up on this issue: restarting the client devices, enabled the connection to be restored

The client shellhub agent could then be forced to update using the following:

```
cat > /home/pi/manual-upgrade-shellhub <<EOF 
docker stop shellhub 
docker rm shellhub 
curl -sSf "https://shellhub.openenergymonitor.org/install.sh?tenant_id=xxxxxxxxxxxx" | sh 
EOF 
chmod a+x /home/pi/manual-upgrade-shellhub 
nohup /home/pi/manual-upgrade-shellhub
``` 

Thanks to the shellhub team for helping to debug this.
