### ISSUE TITLE
Trying to install shellhub-io on raspberry pi 3A+ and get error

### ISSUE THREAD

**Issue by MkLHX** [shellhub-io/shellhub#203]
Hi there i've tested to run the server instance on raspberry pi 3A+ and i get an error about architecture. 
> ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

when i test my os with 
> docker info  -f '{{.OSType}}/{{.Architecture}}'

i get 
>linux/armv7l

So what can i do to manage testing sheelhub-io on raspberry?

**Comment by gustavosbarreto** [comment]
Are you using Raspbian?

**Comment by MkLHX** [comment]
yeah using raspbian buster

```cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by gustavosbarreto** [comment]
@MkLHX  Can you please test this ShellHub docker image running the following command?

```
docker run -d --name=shellhub --restart=on-failure --privileged --net=host --pid=host -v /:/host -v /var/run/docker.sock:/var/run/docker.sock -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -e SERVER_ADDRESS=your_server_address -e PRIVATE_KEY=/host/etc/shellhub.key -e TENANT_ID=replace_with_tenant_id gustavosbarreto/shellhub-arm32v7
```

Make sure to replace `replace_with_tenant_id` with your tenant ID and `your_server_address` with your server address (if you are using ShellHub Hosted the value is `https://cloud.shellhub.io`)

**Comment by MkLHX** [comment]
@gustavosbarreto no problem to insall the shellhub-io agent by using
>curl "https://<my_own_server_istance>/install.sh?tenant_id=<my_tenant_id>" | sh

every works on VPS or digital ocean's docker droplet

i've got an error when i try to host my own shellhub-io server instance on raspberry pi 3A+.
i just follow docs here: https://docs.shellhub.io/installing/

**Comment by gustavosbarreto** [comment]
> @gustavosbarreto no problem to insall the shellhub-io agent by using
> 
> > curl "https://<my_own_server_istance>/install.sh?tenant_id=<my_tenant_id>" | sh
> 
> every works on VPS or digital ocean's docker droplet
> 
> i've got an error when i try to host my own shellhub-io server instance on raspberry pi 3A+.
> i just follow docs here: https://docs.shellhub.io/installing/

I would be thankful if you can help by running that command on your RaspberryPi. if it works I will send the fix that will be available in the next release of ShellHub.

**Comment by MkLHX** [comment]
ok i ran it.
no docker instances on my device.
i ran docker run command.
get the same error
```
pi@raspberrypi:~/shellhub-v0.3.2 $ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
pi@raspberrypi:~/shellhub-v0.3.2 $ docker run -d --name=shellhub --restart=on-failure --privileged --net=host --pid=host -v /:/host -v /var/run/docker.sock:/var/run/docker.sock -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -e SERVER_ADDRESS=http://46.101.175.238 -e PRIVATE_KEY=/host/etc/shellhub.key -e TENANT_ID=c18f4ced-a37a-41db-bc8c-e067b52090cf gustavosbarreto/shellhub-arm32v7
e9f912273ca895a2d957fa3f553f7d6009fff5930dd5173d4073e4d0b9fc7364
pi@raspberrypi:~/shellhub-v0.3.2 $ docker-compose up -d
Pulling mongo (mongo:3.4.19)...
3.4.19: Pulling from library/mongo
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
pi@raspberrypi:~/shellhub-v0.3.2 $

```

**Comment by gustavosbarreto** [comment]
Ok! Thank you!

It seems that ShellHub agent works now in arm32v7 architecture. But I'm not sure if the ShellHub server should work. Its intended to be used in servers only.

@otavio what you think?

**Comment by otavio** [comment]
Indeed, for now we did not expect people to use the server on a Raspberry Pi. Also, mongodb is indeed challenging as it does not support running on 32-bit machines.

**Comment by otavio** [comment]
I'm closing this issue as if there is something we need to improve, this should be reported as a new issue.

**Comment by MkLHX** [comment]
ok so i tested it on digital ocean droplet and everything works perfectly
