### ISSUE TITLE
Cannot open nano text editor on remote terminal: Error opening terminal: xterm.js.

### ISSUE THREAD

**Issue by glynhudson** [shellhub-io/shellhub#2059]
When I try to open nano text editor using a remote shellhub terminal I get the error `Error opening terminal: xterm.js.`. Nano works fine via a local shell. 

![Screenshot from 2022-08-05 14-08-19](https://user-images.githubusercontent.com/758844/183084759-3e0e8304-3101-47a7-8aab-50eb3f7717b6.png)

**Comment by gessecarneiro** [comment]
Hello Glyn. How are you?
I did some tests here, both in the cloud and in the local shell, and in both cases it worked correctly. Given that, I would like to know which Linux distribution you used and which version of ShellHub was used (Cloud or local)?

**Comment by glynhudson** [comment]
Thanks for taking a look. It's a self-hosted system using your docker containers, I've just upgraded to V0.9.5 and the issue persists. The client is a RaspberryPi, This issue effect all my clients which are all RaspberryPis

**Comment by gessecarneiro** [comment]
Hi Glyn. All good?  
In that case, you could test the command below:
`TERM=xterm nano test`

**Comment by glynhudson** [comment]
Yes that worked! Do you know what could be causing this? 

 I'm also having some bizarre terminal issues, when I press backspace the cursor advances! 

Thanks for your help.
