### ISSUE TITLE
Grouping Devices

### ISSUE THREAD

**Issue by andy-freund** [shellhub-io/shellhub#206]
I installed my first device today. It was quick and easy.

I like the fact that you can set the device name individually.

Now I want to add some Raspberry Pi's, some evaluation boards and my workstations.

I am missing a function to group or tag the devices to keep the overview. I would like to be able to distinguish between productive devices and test devices, as well as private devices.

**Comment by apollo17march** [comment]
> I like the fact that you can set the device name individually.

I am not able to name or set alias to my device. How did you do that?

**Comment by gustavosbarreto** [comment]
> > I like the fact that you can set the device name individually.
> 
> I am not able to name or set alias to my device. How did you do that?

Click on Details icon in Devices pages to open device's detail page. From device's page click on the pencil edit icon next to device hostname.

**Comment by gustavosbarreto** [comment]
Closing this issue due to the functionality can be archived by creating namespaces (it will available in `v0.5.0`)

**Comment by gustavosbarreto** [comment]
Closing this issue due to the functionality can be archived by creating namespaces (it will available in v0.5.0)
