### ISSUE TITLE
confusing: v0.9.6-rc.2 is released after v0.9.6

### ISSUE THREAD

**Issue by afriza** [shellhub-io/shellhub#2091]
[v0.9.6](https://github.com/shellhub-io/shellhub/releases/tag/v0.9.6) currently refers to https://github.com/shellhub-io/shellhub/commit/e7957d87c4759a4f97ab6d55e271e84917ec2aa2

and [v0.9.6-rc.2](https://github.com/shellhub-io/shellhub/releases/tag/v0.9.6-rc.2) refers to https://github.com/shellhub-io/shellhub/commit/47fc3b4cbd8b578da8f412ba6835a65a8f095a91

There are [92 commits from v0.9.6 to v0.9.6-rc.2](https://github.com/shellhub-io/shellhub/compare/v0.9.6...v0.9.6-rc.2)

I expected after v0.9.5, comes v0.9.6-rc.1 then v0.9.6-rc.2 and so on until final release v0.9.6

**Comment by otavio** [comment]
The `v0.9.6-rc.2` is indeed newer and will likely become a `v0.10.0-rc.1` next. The `v0.9.6` was a minor release to fix a UI issue.

Next time we'll make sure to use the minor bump directly for the rc releases. Thanks for the feedback!
