### ISSUE TITLE
namespace import

### ISSUE THREAD

**Issue by kashingonline** [shellhub-io/shellhub#2124]
Hi,

We have a shelf hosting shellhub instance and need to recover the namespace. How does on install an old namespace to a new server?

**Comment by gustavosbarreto** [comment]
You need to copy following files from the old server to new server:

* `api_private_key`
* `api_public_key`
* `ssh_private_key`

Also you have to dump the database using the `mongoexport` tool then import into new server using the `mongoimport` tool. This will preserve all your instance data (devices, sessions, users, namespaces).

If you are not interested in keeping database data but only the connection between the new server and your devices just create a namespace on the new server using the same `TENANT_ID` from the old server. To create a new namespace with a predefined `TENANT_ID` run the following command:

```
TENANT_ID=xxxxxx ./bin/add-namespace namespace username
``` 

Replace `xxxxxx` with the old `TENANT_ID`

**Comment by kashingonline** [comment]
Thank you for the prompt response. Is there a way to obtain the TENNANT_ID and namespace name if the interface is not accessible?

**Comment by gustavosbarreto** [comment]
> Thank you for the prompt response. Is there a way to obtain the TENNANT_ID and namespace name if the interface is not accessible?

Do you have access to any device that was connected to old server? If yes, run the following command to obtain the `TENANT_ID`:

```
docker inspect shellhub | grep TENANT_ID
```

**Comment by kashingonline** [comment]
Thank you, as good as new.
