### ISSUE TITLE
Public key configuration

### ISSUE THREAD

**Issue by lucasxteixeira** [shellhub-io/shellhub#2142]
Currently, I'm not able to authenticate using public key, I think I might not configured it properly.
I added my local public RSA key in shellhub and I let it go for all devices and all users.

When I try to login using:
`ssh remote_user@shnamespace.shuser@cloud.bogus.com`
It still asks for the remote_user password.

The keys are properly configured in the final(for the openssh-server standard), because sshd works perfectly.

Am I doing something wrong?
Thank you.

**Comment by lucasxteixeira** [comment]
Latest version (0.12.0), I did fresh install this morning.

**Comment by lucasxteixeira** [comment]
Sorry, I mistyped it, it is indeed 0.10.2.

I'm not entire familiar with the different key types, but I generated it a couple of years ago using ssh-keygen -t rsa
`2048 SHA256:BGmvHIkg8ShVbCz/2wMrZHoS+3dEpvpntn/jpE0FsNc id_rsa.pub (RSA)`

**Comment by lucasxteixeira** [comment]
Upon further investigation, I found the following:
`send_pubkey_test: no mutual signature algorithm`

I generated a new key pair using ED25519 and it works.

Is that intentional? 
I know that ED25519 is better performance-wise but RSA is almost universally standard.

**Comment by gustavosbarreto** [comment]
> I'm not entire familiar with the different key types, but I generated it a couple of years ago using ssh-keygen -t rsa
2048 SHA256:BGmvHIkg8ShVbCz/2wMrZHoS+3dEpvpntn/jpE0FsNc id_rsa.pub (RSA)

It's seems you are using a RSA-SHA-1 key which is considered unsafe.
The recent versions of openSSH and other tools does not support RSA-SHA1 keys anymore. See https://www.zdnet.com/article/openssh-to-deprecate-sha-1-logins-due-to-security-risk/

It's recommended to use RSA-SHA2 keys or ED25519 instead.

**Comment by lucasxteixeira** [comment]
Understood, thank you and sorry to bother you guys.
