### ISSUE TITLE
[Feature] Custom keep alive intervall

### ISSUE THREAD

**Issue by jwillmer** [shellhub-io/shellhub#215]
To limit bandwidth we would like to change the interval the device is calling home. For us it would be totally fine if the device only contacts the server once every hour. 

To access the shell there could be two options:
- let the server know to establish a ssh connection next time he calls home and notify the user that a ssh session has been established
- let the user predefine commands he likes to sent to the server. Next time the server calls home he will then execute them.

Related [question](https://github.com/shellhub-io/shellhub/issues/102)

**Comment by gustavosbarreto** [comment]
I was wondering where to put that option:

1) In the one line install script
2) In the settings page or ShellHub UI

**Comment by otavio** [comment]
I think it'd be nice if it'd be configurable on the settings page as it could receive it when "going home".

Imagine when it uses the keep-alive, the API server might reply to the agent with settings override. It could start small but provide a solid foundation for the future.

Thoughts?

**Comment by jwillmer** [comment]
Thinger.io does a good job to display the device state in the GUI. I think you could copy part of the concept:
![image](https://user-images.githubusercontent.com/1503577/87853368-96cb0e80-c909-11ea-8490-dac2075810db.png)
![image](https://user-images.githubusercontent.com/1503577/87853373-a3e7fd80-c909-11ea-97ca-2b549f7a2808.png)

Device state is considered "online/active" as long as the timeout is not reached.
