### ISSUE TITLE
Allow to easy override the port used for the server on docker-compose

### ISSUE THREAD

**Issue by otavio** [shellhub-io/shellhub#226]
It is common people need to deploy the server where they need to use a different port. It'd be good to offer an easy way to do that.

Also, this should be added to the FAQ list on the docs.

**Comment by gustavosbarreto** [comment]
https://github.com/shellhub-io/shellhub/blob/8e00f0bbe6f151aace836fe51efa3ff9e5d825d5/.env#L2
