### ISSUE TITLE
make build always finish with error

### ISSUE THREAD

**Issue by likid** [shellhub-io/shellhub#2262]
I'm trying to build in an arm64 machine, but I always get the same error:

```
#0 50.25 go: downloading google.golang.org/protobuf v1.26.0
#0 109.7 # github.com/golangci/golangci-lint/cmd/golangci-lint
#0 109.7 /usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
#0 109.7 collect2: fatal error: cannot find 'ld'
#0 109.7 compilation terminated.
#0 109.7
------
failed to solve: executor failed running [/bin/sh -c go install github.com/markbates/refresh@v1.11.1 &&     go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1]: exit code: 2
make: *** [Makefile:59: build] Error 17
```
```
go version
go version go1.16.5 gccgo (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 linux/arm64
```

**Comment by likid** [comment]
I've updated go, but I've got the same error.

`go version go1.18.1 linux/arm64`

```
#0 20.18 go: downloading github.com/mattn/go-runewidth v0.0.9
#0 20.23 go: downloading google.golang.org/protobuf v1.26.0
#0 95.01 # github.com/golangci/golangci-lint/cmd/golangci-lint
#0 95.01 /usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
#0 95.01 collect2: fatal error: cannot find 'ld'
#0 95.01 compilation terminated.
#0 95.01
```
`Linux andersonvm 5.15.0-1021-oracle #27-Ubuntu SMP Fri Oct 14 20:04:20 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

Shellhub version 0.10.3 as of https://docs.shellhub.io/self-hosted/deploying

**Comment by likid** [comment]
It's already installed

`binutils-aarch64-linux-gnu/jammy-updates,jammy-security,now 2.38-4ubuntu2 arm64 [installed,automatic]`

**Comment by benasse** [comment]
Could you try to install a 1.19.x version of go ?
It looks like the following issue : https://github.com/golang/go/issues/52399 ( resolved in https://github.com/golang/go/issues/22040 )

**Comment by gustavosbarreto** [comment]
I guess you are trying to build the ShellHub server on an unsupported architecture.

**Comment by likid** [comment]
same error with go 1.19
`go version go1.19.2 linux/arm64`

docker images are available only for AMD64 arch, not for ARM64, so I have to build them.

**Comment by gustavosbarreto** [comment]
> docker images are available only for AMD64 arch, not for ARM64, so I have to build them.

ShellHub Server: does not support architectures other than AMD64 (if you want to implement this go ahead)
ShellHub Agent: amd64, armv6, armv7, arm64

**Comment by benasse** [comment]
FYI, Although it is not supported, I managed to run shellhub binary on old 386 host.
