### ISSUE TITLE
Why do you make the program run on port 22?

### ISSUE THREAD

**Issue by gakiyukr** [shellhub-io/shellhub#2334]
### Description

Why do you make the program run on port 22?
What link do I use to connect SSH running on port 22?
And why there is no configuration file for related configurations, but users need to modify variables by themselves?

### Edition

Community

### Version

v0.10.9

**Comment by gustavosbarreto** [comment]
Hi! @gakiyukr 

> Why do you make the program run on port 22?

This is the default for an SSH server. But you can easily change this by editing the `SHELLHUB_SSH_PORT` environment variable in the `.env.override` configuration file.

> What link do I use to connect SSH running on port 22?

I didn't understand what you meant.

> And why there is no configuration file for related configurations, but users need to modify variables by themselves?

Yes, there is a configuration file. Please follow this link: https://docs.shellhub.io/self-hosted/configuring

If you have any questions please don't hesitate to reopen this issue and leave a comment.
