### ISSUE TITLE
Can't add user with ./bin/add-user, password is invalid

### ISSUE THREAD

**Issue by peterge1998** [shellhub-io/shellhub#2346]
### Description

After deploying, I can't add a user:
```
root@shellhub:~/shellhub# ./bin/add-user peterge <PASSWORD> mail@peterge.de
INFO[0000] Setting log level                             log_level=info
Command "add-user" is deprecated, This command is deprecated and will be removed in a future release.
Error: user password is invalid
Usage:
  cli add-user [flags]

Flags:
  -h, --help   help for add-user

ERRO[0000] user password is invalid
```
`<PASSWORD>` is a string from 35 randomly generated random letters/capital letters, no digits/special chars at all.

Adding a user with `password` as password works. What is the min/max length? I think there should be no max length set at all, at least name them in the documentation!

### Edition

Community

### Version

v0.10.9

**Comment by henrybarreto** [comment]
Hello, @peterge1998.

Currently, the rules for password are rather permissive. The password can have any character, but the string length should be between 5 and 30 characters.

**Comment by henrybarreto** [comment]
In the next release, we'll improve the new CLI command to report better errors related to formation.
