### ISSUE TITLE
Loading the namespace list has failed

### ISSUE THREAD

**Issue by peterge1998** [shellhub-io/shellhub#2348]
### Description

```
root@shellhub:~/shellhub# ./bin/add-namespace test peterge       
INFO[0000] Setting log level                             log_level=info
Command "add-namespace" is deprecated, This command is deprecated and will be removed in a future release.
Namespace added: test
Owner: 63ba87a77d609cc3e930d176
Tenant ID: 2edc7a03-1adb-49db-b86c-294702ffdc85
```
Adding a namespace leads to this Error:
![image](https://user-images.githubusercontent.com/47355238/211188623-e5276884-078e-4e6e-a2a5-b6365a0e85d4.png)

### Edition

Community

### Version

v0.10.9

**Comment by peterge1998** [comment]
Okay, test is listed on the top right. Did not see it at all (because its collapsed):
![image](https://user-images.githubusercontent.com/47355238/211188826-a1cdf94b-2f2a-4f4d-ad7f-e966dfabd44f.png)

But why did I get the error?

**Comment by peterge1998** [comment]
When adding a namespace with a `.` in its name, I get `ERRO[0000] namespace is invalid`. Why? Please mention naming convention in the docs!

**Comment by peterge1998** [comment]
Wait, there is [RFC1123](https://tools.ietf.org/html/rfc1123) linked at https://shellhub-io.github.io/getting-started/creating-namespace/ :)
Why not at https://docs.shellhub.io/self-hosted/administration?

**Comment by peterge1998** [comment]
Is shellhub.gerhards.lan not a valid hostname?

**Comment by henrybarreto** [comment]
- [x] add warning informing about RFC1123 when add namespace to documentation
- [ ] fix get empty namespace
