### ISSUE TITLE
Using ShellHub with macOS failed

### ISSUE THREAD

**Issue by andy-freund** [shellhub-io/shellhub#242]
I installed docker at macOS 10.15.6, than the ShellHub image.
It started and connected to ShellHub.

If I try to connect the Terminal I will not work. Allway permission denied.
I use a valid user with correct password.

If I try to connect via SSH local in my network from an other device, it works fine.

**Comment by otavio** [comment]
@andy-freund, currently the use of the agent is tested only on Linux however it'd be nice to figure out what it'd take to support macOS or even Windows (now that WSL2 is available).

I marked this as an enhancement, so we take a look at this in future.

**Comment by gustavosbarreto** [comment]
I think ShellHub shouldn't be supported on other platforms than Linux. 

According to the project description: "ShellHub enables teams to easily access any Linux device behind firewall and NAT"

It doesn't make sense to me to support Windows or MacOS.

**Comment by otavio** [comment]
@gustavosbarreto I don't think this should be a priority for now but if technically possible, it'd be nice to extend the support in the future.
