### ISSUE TITLE
When I run a command via ssh the result is not always displayed

### ISSUE THREAD

**Issue by benasse** [shellhub-io/shellhub#2509]
### Description

My server and my shellhub agent are in version v0.11.1.

When I run a command on my agent via my shellhub server the result of the command does not always reach my ssh client.

I suspect a race condition when the agent closes the connection, but I haven't been able to get the necessary logs to confirm or deny my theory.

The problem is quite easily reproducible in my environment by typing several times in a row a command of this type:

```
 ssh user@ns.agent@server date
```

Below the end of the logs of a command launched with the -v option of ssh, for the 2nd case, we see that the answer is not sent by the server.
OK:
```
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending command: date
Wed Feb 22 22:45:22 CET 2023
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2852, received 1756 bytes, in 3.0 seconds
Bytes per second: sent 943.4, received 580.9
debug1: Exit status 0
```
KO:
```
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending command: date
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2852, received 1704 bytes, in 9.4 seconds
Bytes per second: sent 303.0, received 181.0
debug1: Exit status 0
```

Can you reproduce the problem and what do you think?

### Edition

Community

### Version

v0.11.1

**Comment by gustavosbarreto** [comment]
Hi @benasse, we are currently debugging this issue and will have a fix out soon

**Comment by benasse** [comment]
Hi @gustavosbarreto, your reactivity is amazing, thank you for your involvement ! 🤩 

My long term dream would be to be able to run ansible through shellhub but I think the way to get there will not be easy.
I'm going to do some tests and go step by step.
When I have some content, I think I will open a discussion to share my progress on the subject. It may interest other people.

**Comment by gustavosbarreto** [comment]
Hi @benasse, can you test test the latest release candidate version (`v0.11.2-rc.1`)?

**Comment by benasse** [comment]
Hi @gustavosbarreto, I made the upgrade and just tested to execute the date command like in my first post, the success rate is a bit better. But it is not yet 100%.

If it helps, the ssh client and agent logs are available below:

https://gist.github.com/benasse/fb2b162f5697f35a6f71ce697fe56a2c

**Comment by benasse** [comment]
Anyway, I didn't make the effort to quantify it but when I launch a normal ssh connection, it works, much better than before the patch.
This is ok in a "normal" use case.

**Comment by otavio** [comment]
We are considering doing a release due to this considerable improvement. But, next, we want to continue improving it for the next release.

**Comment by gustavosbarreto** [comment]
Hi @benasse, can you please test the latest release candidate version (v0.11.3-rc.1)?

**Comment by benasse** [comment]
I @gustavosbarreto I tested the release candidate, but it remains random 😕

Below are the agent-side logs: https://gist.github.com/benasse/c97c12dbd4d4b7b00276188e07dd8e5b

**Comment by gustavosbarreto** [comment]
> I @gustavosbarreto I tested the release candidate, but it remains random 😕
> 
> Below are the agent-side logs: https://gist.github.com/benasse/c97c12dbd4d4b7b00276188e07dd8e5b
> 
> 
> 
> 

Please ensure that the agent version matches the server version, as the fix was implemented in the agent.

**Comment by benasse** [comment]
I double checked, I built the agent from the master branch directly on the host on which I did my tests.
This server is running Debian 10.

![image](https://user-images.githubusercontent.com/5676729/222371372-4b2faf18-2c8e-4338-bbe5-51fe6c88a332.png)

![image](https://user-images.githubusercontent.com/5676729/222372199-5198e2eb-cc0f-44bb-894d-ad7418857710.png)

**Comment by gustavosbarreto** [comment]
I am reopening this issue because I was able to confirm the same problem. The PR '#2532' fixes another issue related to this one that was discovered during the investigation of this issue.
