### ISSUE TITLE
Cannot connect to device with SSHID

### ISSUE THREAD

**Issue by disideris** [shellhub-io/shellhub#254]
How can i use sshid of a device to remote connect to it?

**Comment by otavio** [comment]
Take a look at http://docs.shellhub.io/guides/connecting-device/#command-line-ssh-client

I hope it helps.

**Comment by disideris** [comment]
doesn't work

**Comment by otavio** [comment]
What command did you use?

**Comment by disideris** [comment]
i tried all variations of the cryptic :) documentation.

Can you please clarify what is the correct way?

My ssh port mapping is 22:2222

For example in my shellhub i have a device with sshid 
username.00000001@212.212.212.212

My device's account is pi

i tried to ssh with:

ssh username.00000001@212.212.212.212

ssh pi@username.00000001@212.212.212.212

ssh -p 2222 pi@username.00000001@212.212.212.212
 
ssh -p 2222 username.00000001@212.212.212.212

Nothing works!

**Comment by otavio** [comment]
If it is a Raspian, it should be:

```
ssh -l pi@username.00000001 212.212.212.212
```

or

```
ssh pi@username.00000001@212.212.212.212
```

Both should work.

**Comment by disideris** [comment]
Unfortunately 

Invalid session target
Connection to 212.212.212.212 closed.

**Comment by leonardojoao** [comment]
Hello @disideris,
On devices in the page list, is your device showing up online?

**Comment by disideris** [comment]
Yes and i can connect to the device through the embedded terminal

**Comment by gustavosbarreto** [comment]
> i tried all variations of the cryptic :) documentation.

Could you help us on decrypting the documentation?

**Comment by gustavosbarreto** [comment]
> Yes and i can connect to the device through the embedded terminal

Do you have any firewall rule configured?

**Comment by disideris** [comment]
Yes sure! 
I think two things would make the doc clear:
1. Specify which port one should use to remote ssh according to docker-compose.yml
2. An example with real-ish hostnames and ip's like above

**Comment by disideris** [comment]
> > Yes and i can connect to the device through the embedded terminal
> 
> Do you have any firewall rule configured?

No. I am trying sth from my side. I don't think its a bug. 
I will close the issue when i confirm its my issue

Thanks a lot

**Comment by disideris** [comment]
It was my issue. I modified agent.go to get serial number instead of mac of my device and there was a newline as part of the username. Now i  can login through sshid. Thanks for the help and repsonses!

**Comment by otavio** [comment]
> Yes sure!
> I think two things would make the doc clear:
> 
>     1. Specify which port one should use to remote ssh according to docker-compose.yml
> 
>     2. An example with real-ish hostnames and ip's like above

Maybe you could offer a PR on https://github.com/shellhub-io/shellhub-io.github.io proposing some improvements? It'd be of great help.

**Comment by gustavosbarreto** [comment]
> It was my issue. I modified agent.go to get serial number instead of mac of my device and there was a newline as part of the username. Now i can login through sshid. Thanks for the help and repsonses!

It would be nice if you open a PR with your changes to agent source code. Maybe other people need it. It would both benefit you as you wouldn't need to keep your fork up-to-date with upstream

**Comment by AntoinedeChassey** [comment]
+1
Would love to have some details on how you managed to make it work @disideris :)
Suffering with this too.
