### ISSUE TITLE
Users are deleted when mongo docker goes down and up again

### ISSUE THREAD

**Issue by disideris** [shellhub-io/shellhub#255]
When i run docker-compose down and then up again i cannot login to shellhub. I checked the users collections in mongo container and it is empty whereas devices seem to be ok!

**Comment by gustavosbarreto** [comment]
This is expected behaviour when you use `docker-compose down` command.

See: https://docs.docker.com/compose/reference/down/

Are you confused about the difference between `stop` and `down` commands?

See: https://docs.docker.com/compose/reference/stop/

**Comment by disideris** [comment]
Ok thanks!
