### ISSUE TITLE
[feature] Supply agent DeviceIdentity via docker environment variable

### ISSUE THREAD

**Issue by simora** [shellhub-io/shellhub#259]
I'm interested in this as a AWS/Azure bastion host solution. My only concern is if I have devices spinning up and registering as new clients I would like them registered with a friendly name rather than a mac address. The potential for name collisions can happen but that should be my problem to solve through SSoT or other mechanisms.

**Comment by otavio** [comment]
What kind of friendly name you would like to have?

**Comment by simora** [comment]
Something that will be username friendly. [a-zA-Z0-9\-]+ is plenty fine with me. I would prefer an arbitrary string. I would set it through AWS userdata on instance creation and use a script to create the docker container using the values from userdata.

**Comment by otavio** [comment]
This is indeed a nice idea. For us to design the feature we need to clarify a few aspects: for device identity we need it to be a unique value and this is the reason we adopted the MAC as the source for this data.

Considering you'll be setting this when launching the service, you need to make sure it is unique. Does it sound Ok?

**Comment by simora** [comment]
Yup. I plan to use Terraform to generate the systems and have an incrementing serialization. Uniqueness won't be an issue. The collision should only exist within my tenancy on the Shellhub hosted service correct? I would assume the same would apply for the self-hosted option as well?

**Comment by simora** [comment]
If you are looking for use cases to justify the LoE how about AWS instances identifying by AWS instances id extracted from userdata API within the host. Would simplify the identification of systems.
I prefer my previous example as a means to help reduce the number of AWS users who have unnecessary access to the corporate account by identifying the system by function, application or deployment tier (prod, int, dev).

**Comment by otavio** [comment]
@simora you mentioned you intend to use Terraform to install it. Maybe we could add the Terraform Provider at our organization here so more people can benefit from it.

Does it make sense to you?

**Comment by simora** [comment]
I was just going to have it install via script after instance creation. Have docker installed and the ami prepped with Packer ready to run. Keep it simple. No need to rewrite what has already been masterfully crafted.
