### ISSUE TITLE
Device changes hostname every restart

### ISSUE THREAD

**Issue by tiago-cerveira** [shellhub-io/shellhub#2833]
### Description

Some devices change their hostname every time they are restarted while others don't.

This means their entry from device list is no longer valid and a new entry appears in the pending list. All tags associated need to be re entered and connection credentials need to be updated.

### Edition

Cloud

### Version

v0.12.2-rc.3

**Comment by otavio** [comment]
Hi @tiago-cerveira, by default, ShellHub utilizes the MAC address of the primary interface as its identifier. Therefore, if the identifier changes, the name changes as well.

Which device are you currently installing the ShellHub agent on?

**Comment by tiago-cerveira** [comment]
I am getting device change for jetson xavier devices

Otavio Salvador ***@***.***> escreveu no dia quinta,
25/05/2023 à(s) 12:17:

**Comment by otavio** [comment]
Can you please check the output of `ifconfig -a` before and after a reboot? I think the MAC address might change.

**Comment by facelabs** [comment]
@tiago-cerveira I had similar scenario, and it was not possible to remove dummy0 since it was pre-compiled with the kernel. the workaround I used is with the SHELLHUB_PREFERRED_HOSTNAME parameter, I did something like SHELLHUB_PREFERRED_HOSTNAME=$(hostname) in an automation on the relevant machines.

**Comment by otavio** [comment]
To ensure a long-term solution, it is essential to update the `SHELLHUB_PREFERRED_IDENTITY`, which serves as the device identifier. You can provide a CPU serial number, network MAC address, or any other equivalent identifier to complete the process.

In one of our customers we use:
```sh
#!/bin/sh

# This script set the CPU serial number as ShellHub ID
# If it is a RaspberryPi based machine, it reads from /sys/firmware or /sys/devices/ path
if [ -e /sys/firmware/devicetree/base/serial-number ]; then
    export SHELLHUB_PREFERRED_IDENTITY=$(tr -d '\0' < /sys/firmware/devicetree/base/serial-number)
else
    export SHELLHUB_PREFERRED_IDENTITY=$(cat /sys/devices/soc0/serial_number)
fi
```

**Comment by otavio** [comment]
Closing as it is a device characteristic and we offered a way to fix it.
