### ISSUE TITLE
Upper-case letters in device names cause "Invalid session target" failure

### ISSUE THREAD

**Issue by sixhills** [shellhub-io/shellhub#284]
I'm not sure if this is a minor bug or a undocumented restriction but device names containing upper-case letters don't work. For example, if I rename a device in the web UI from its default MAC address to something more readable, like "Pi41", and attempt to ssh to it from another host using the "ssh user@SSHID" syntax, the connection fails with "Invalid session target". Renaming the device to "pi41" works.

**Comment by gustavosbarreto** [comment]
@eduardoveiga  We have to ensure that device's hostname are all uppercase before saving

**Comment by gustavosbarreto** [comment]
@leonardojoao Also we need to put a helper text in the rename dialog warning the user about that hostname iis case-insensitive

**Comment by eduardoveiga** [comment]
> @eduardoveiga  We have to ensure that device's hostname are all lowercase before saving

Ok

**Comment by leonardojoao** [comment]
> @leonardojoao Also we need to put a helper text in the rename dialog warning the user about that hostname is case-insensitive

Do I put permanent text or when I insert a capital letter, warn the message?

**Comment by otavio** [comment]
I am not sure we ought to ignore the case on the rename. I think some people might wish to use it to easy the device visual lookup.

What I propose is when connecting, the `api` should use all in lowercase. So the user can use upper and lower case but when resolving the device identity it is ignored.

**Comment by eduardoveiga** [comment]
I put a validation in API
now, when a user insert a name with some capital letter the renaming is ignored, but I think in UI there's and advice only when the users write some capital letter (same form we use to RFC 1123)

**Comment by otavio** [comment]
After discussion with @gustavosbarreto we agreed on:

- forced lowercase on DB;
- we should warn the user about RFC 952 on `ui`
- we need to add a migration on DB to fix previous uses of upper case

Sounds good?

**Comment by eduardoveiga** [comment]
actually we use RFC 1123
we should change rfc1123 to rfc952?

**Comment by eduardoveiga** [comment]
RFC1123 allows hostnames started with digits and RFC952 don't, right? 
so in this case can broke many hostnames, including default from mac address
