### ISSUE TITLE
Cant add device, doesn't appear

### ISSUE THREAD

**Issue by skanthem** [shellhub-io/shellhub#2858]
### Description

Installed agent using provided tenant script onto a raspberry pi 4 in docker. Agent is up, but device is not showing up in account. Docker container log shows the following:
time="2023-06-02T18:35:26Z" level=info msg="Setting log level" log_level=info
time="2023-06-02T18:35:26Z" level=info msg="Starting ShellHub" mode=multi-user version=v0.12.2-rc.3
2023/06/02 18:35:26.704913 ERROR RESTY Get "http://api:8080/info?agent_version=v0.12.2-rc.3": dial tcp: lookup api on 208.91.112.53:53: no such host, Attempt 1

Error repeats in log every 2 seconds. I can ping 208.91.112.53 from the pi. Firewall doesn't appear to be blocking anything. Tried shutting down nginx just in case, tried disconnecting my ssh session into the pi just in case, still no result. Note that I had accidentally deleted this device in my web account, and it was working before. Due to other issues I had to re-image the device anyway, and now getting this issue.

Thanks!

### Edition

Community

### Version

v0.12.2-rc.3

**Comment by sirluky** [comment]
Currently there is a bug in Shellhub, it gives bad url to the endpoint. 
I don't know how to edit it in sourcecode, but you can easily edit line in the generated script yourself.

1. open link from curl script `https://cloud.shellhub.io/install.sh?tenant_id=00000-000...`
2. edit line SHELLHUB_SERVER_ADDRESS= to your endpoint instead api:8080, eg. cloud.shellhub.io

**Comment by sirluky** [comment]
Currently there is a bug in Shellhub, it gives bad url to the endpoint. 
I don't know how to edit it in sourcecode, but you can easily edit line in the generated script yourself.

1. open link from curl script `https://cloud.shellhub.io/install.sh?tenant_id=00000-000...`
2. edit line SHELLHUB_SERVER_ADDRESS= to your endpoint instead api:8080, eg. cloud.shellhub.io
3. copy content from edited script and run it. 
4. enjoy

**Comment by gustavosbarreto** [comment]
Bug confirmed, I can reproduce it.

**Comment by skanthem** [comment]
Thanks for the update!In the meantime, I’ll try the suggested workaround.Sent from my iPhoneOn Jun 5, 2023, at 8:31 AM, Otavio Salvador ***@***.***> wrote:﻿
Hey there, just wanted to give you an update on the issue you reported. @gustavosbarreto was able to reproduce it and we are actively working on finding a fix for it. However, I wanted to let you know that we are currently making some major changes to the frontend (UI) and need to finish those before we can release a new rc version. Thanks for your patience and understanding!

**Comment by skanthem** [comment]
This worked for me:

Loaded script into a file (except using my actual tenant ID instead of all zeroes):
curl -sSf "https://cloud.shellhub.io/install.sh?tenant_id=00000000-0000-0000-0000-000000000000" > shellhubscript
Then extracted the file’s "sudo docker run" command, changing “api:8080” to “cloud.shellhub.io <http://cloud.shellhub.io/>”
Then executed that command on the pi, like so:

sudo docker run -d \
        --name=shellhub \
        --restart=on-failure \
        --privileged \
        --net=host \
        --pid=host \
        -v /:/host \
        -v /dev:/dev \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /etc/passwd:/etc/passwd \
        -v /etc/group:/etc/group \
        -v /etc/resolv.conf:/etc/resolv.conf \
        -v /var/run:/var/run \
        -v /var/log:/var/log \
        -e SHELLHUB_SERVER_ADDRESS=http://cloud.shellhub.io \
        -e SHELLHUB_PRIVATE_KEY=/host/etc/shellhub.key \
        -e SHELLHUB_TENANT_ID=00000000-0000-0000-0000-000000000000 \
        shellhubio/agent:v0.12.2-rc.3

**Comment by otavio** [comment]
Hello @skanthem, it appears that the issue you are experiencing may not be related to your current situation. However, it's worth noting that the DNS seems to be unreachable, which could indicate a larger issue with the network.

**Comment by skanthem** [comment]
Yes, that’s just the error it showed when my Internet was down as the router was resetting. Not really an error, I just sent that in so you could verify that the connection attempts looked correct.I am still unable to connect. Had to remove the service and using a different provider for now. skanthOn Jun 6, 2023, at 6:41 AM, Otavio Salvador ***@***.***> wrote:﻿
Hello @skanthem, it appears that the issue you are experiencing may not be related to your current situation. However, it's worth noting that the DNS seems to be unreachable, which could indicate a larger issue with the network.

**Comment by otavio** [comment]
Oh good. But once the network returned, it didn't return to work?

**Comment by skanthem** [comment]
Correct. Tried several times. Other network functions worked fine.Sent from my iPhoneOn Jun 7, 2023, at 9:16 PM, Otavio Salvador ***@***.***> wrote:﻿
Oh good. But once the network returned, it didn't return to work?

**Comment by otavio** [comment]
Once you removed and readded the Docker container, it worked?

**Comment by otavio** [comment]
We're closing this due to lack of response. The issue has been fixed in 0.12.2.
