### ISSUE TITLE
Cannot establish SSH session 

### ISSUE THREAD

**Issue by facelabs** [shellhub-io/shellhub#2873]
### Description

Using the bundle installation, I cannot establish an SSH session. The device does come online and is "Accepted", but after I click on it in the devices list and put in the username:pass, the process crashes. 
I can see the following in the logs - 

Jun 05 20:34:16 machine runc[783]: time="2023-06-05T20:34:16Z" level=info msg="Accepted password" user=admin
Jun 05 20:34:16 machine runc[783]: time="2023-06-05T20:34:16Z" level=info msg="New session request"
Jun 05 20:34:16 machine runc[783]: time="2023-06-05T20:34:16Z" level=warning msg="open /dev/pts/1: no such file or directory"
Jun 05 20:34:16 machine runc[783]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 05 20:34:16 machine runc[783]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84a8f8]
Jun 05 20:34:16 machine runc[783]: goroutine 104 [running]:
Jun 05 20:34:16 machine runc[783]: os.(*File).Name(...)
Jun 05 20:34:16 machine runc[783]:         /usr/local/go/src/os/file.go:56
Jun 05 20:34:16 machine runc[783]: github.com/shellhub-io/shellhub/agent/server.(*Server).sessionHandler(0x40004bd1a0, {0xaba270, 0x400011dba0})
Jun 05 20:34:16 machine runc[783]:         /go/src/github.com/shellhub-io/shellhub/agent/server/server.go:161 +0x12b8
Jun 05 20:34:16 machine runc[783]: github.com/gliderlabs/ssh.(*session).handleRequests.func1()
Jun 05 20:34:16 machine runc[783]:         /go/pkg/mod/github.com/shellhub-io/ssh@v0.0.0-20230224143412-edd48dfd6eea/session.go:263 +0x34
Jun 05 20:34:16 machine runc[783]: created by github.com/gliderlabs/ssh.(*session).handleRequests
Jun 05 20:34:16 machine runc[783]:         /go/pkg/mod/github.com/shellhub-io/ssh@v0.0.0-20230224143412-edd48dfd6eea/session.go:262 +0x52c
Jun 05 20:34:16 machine systemd[1]: shellhub-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 05 20:34:16 machine systemd[1]: shellhub-agent.service: Failed with result 'exit-code'.
Jun 05 20:34:17 machine systemd[1]: shellhub-agent.service: Service hold-off time over, scheduling restart.
Jun 05 20:34:17 machine systemd[1]: shellhub-agent.service: Scheduled restart job, restart counter is at 1.

- Ubuntu 18.04
- Linux machine 4.4.194 #2 SMP Mon Jul 25 21:07:53 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

Any ideas?

### Edition

Community

### Version

v0.12.1

**Comment by gustavosbarreto** [comment]
Please note that the bundle installation method using the `install.sh` script is not officially supported yet and should not be used in production environment. You have been warned. It will become the default method soon, but it's not yet.

The recommended script is the one-line install script obtained by clicking on "Add Device" button in the UI.

That being said, if you are a developer trying to debug an issue, I suggest you running the `install.sh` script with the `RUNC_VERSION=v.1.1.7` env variable to use the latest version of runc, as I suspect the problem may be related to the current version being used `v1.1.2`.

**Comment by facelabs** [comment]
I upgraded the RUNC version to 1.1.7, unfortunately it still fails with the same error 

I guess I will just stick with the docker deployment
