### ISSUE TITLE
Cannot add a device to shellhub cloud portal

### ISSUE THREAD

**Issue by harsh18262** [shellhub-io/shellhub#2879]
### Description

Error message: This namespace has maximum number of devices on your free account

Current no. Of devices added : 1

### Edition

Cloud

### Version

Latest

**Comment by harsh18262** [comment]
Note: I am using a custom built docker image on the node

**Comment by gustavosbarreto** [comment]
> ### Description
> Error message: This namespace has maximum number of devices on your free account
> 
> Current no. Of devices added : 1
> 
> ### Edition
> Cloud
> 
> ### Version
> Latest

@harsh18262 Our free account usage policy has been updated. Going forward, we now track the total number of devices used within a 30-day period. Even if you remove a device, it will still count towards your device limit until the next cycle. As per the new policy, you are allowed a maximum of 3 unique devices.

**Comment by otavio** [comment]
We had to start tracking the total number of devices used within a 30-day period because some users were removing devices and avoiding subscribing, which was causing some issues.

**Comment by harsh18262** [comment]
Is there anyway to re add a device if connection has been broken once or a tenant id is lost?

**Comment by otavio** [comment]
@harsh18262 please open a discussion about this last comment, so we can help you there.
