### ISSUE TITLE
Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by markusglaetzner** [shellhub-io/shellhub#2914]
### Description

docker and docker-compose are installed, git clone is done (testet with v0.12.2 and v0.12.3), changed to dir "shellhub", command "make keygen" executed, command "make start" (with and without sudo) results in:

./bin/docker-compose: 30: Syntax error: redirection unexpected
make: *** [Makefile:43: start] Error 2

### Edition

Community

### Version

v0.12.2 and v0.12.3

**Comment by gustavosbarreto** [comment]
@markusglaetzner Just to confirm, is `dash` your default shell?

**Comment by otavio** [comment]
@markusglaetzner see if #2915 helps.

**Comment by markusglaetzner** [comment]
I always use bash.Am 23.06.2023 um 19:45 schrieb Luis Gustavo S. Barreto ***@***.***>:﻿
@markusglaetzner Just to confirm, is dash your default shell?

**Comment by markusglaetzner** [comment]
I use bash.Am 23.06.2023 um 21:17 schrieb Otavio Salvador ***@***.***>:﻿
@markusglaetzner see if #2915 helps.

**Comment by gustavosbarreto** [comment]
> I always use bash.

No matter if you're using bash in your terminal or not, it looks like your `/bin/sh` is pointing to `dash`. Could you please check the symbolic link of `/bin/sh` by running following command?

```
ls -la /bin/sh
```

I was able to reproduce your issue by using `dash` directly:

```
$ dash bin/docker-compose
bin/docker-compose: 30: Syntax error: redirection unexpected
```

**Comment by markusglaetzner** [comment]
I now understand what you meen and yes /bin/sh points to dash, what seems the standard under Ubuntu. And what would be the solution in this case?

 

Von: Luis Gustavo S. Barreto ***@***.***> 
Gesendet: Freitag, 23. Juni 2023 21:41
An: shellhub-io/shellhub ***@***.***>
Cc: Markus Glaetzner ***@***.***>; Mention ***@***.***>
Betreff: Re: [shellhub-io/shellhub] Syntax error: redirection unexpected (Issue #2914)

 

I always use bash.

No matter if you're using bash in your terminal or not, it looks like your /bin/sh is pointing to dash. Could you please check the symbolic link of /bin/sh by running following command?

ls -la /bin/sh

I was able to reproduce your issue by using dash directly:

$ dash bin/docker-compose
bin/docker-compose: 30: Syntax error: redirection unexpected

**Comment by otavio** [comment]
@markusglaetzner https://github.com/shellhub-io/shellhub/pull/2916 fixes this.

**Comment by markusglaetzner** [comment]
Ok, after changing symbolic link /bin/sh to bash (instead of dash) the start-script works just fine. Thanks for your competent and very fast helf - that´s really great :-)

**Comment by peterge1998** [comment]
Had the same problem. Used these commands to fix it on Debian:
```
sudo update-alternatives --install /bin/sh sh /bin/bash 100
sudo update-alternatives --config sh
```
