### ISSUE TITLE
agent: Appears to hang on startup if unable to connect to server

### ISSUE THREAD

**Issue by sixhills** [shellhub-io/shellhub#298]
In the event of a name resolution failure, timeout or "connection refused", the agent appears to hang on initial startup without providing any error message.

This is unlikely to happen when using the cloud server but is more likely with a mis-configured self-hosted server and the agent provides no clue about the failure - it just hangs.

The apparent hang occurs during the GET of http://server/info and results from the use of a retryable http client with a very large retry count.  The client actually performs 2^31 retries with an exponential backoff but logging is suppresed ("retryClient.Logger = nil" in the NewClient function in client.go), so nothing is visible to the user.

While use of a retryable http client makes the client resilient against transient server outages, it may be useful for the client to report failure to connect on startup.  Would it be acceptable to use the standard http client for the initial cli.GetInfo(), with logging enabled (and exit on failure), and then switch to the retryable client with logging suppressed thereafter?

**Comment by otavio** [comment]
Would be feasible to stick to the retryable client with log enabled?

**Comment by sixhills** [comment]
Would users expect the agent to keep on retrying after an initial failure to connect or would they expect it to log an error and exit?

**Comment by otavio** [comment]
> Would users expect the agent to keep on retrying after an initial failure to connect or would they expect it to log an error and exit?

We should report to the user about the failure but keep trying to connect. For example, consider we had a power failure and Internet takes some time to be available, once it is available it should become connected to the Cloud.

**Comment by sixhills** [comment]
The question then is why it was decided to suppress logging in the http client and is there any disadvantage in enabling it?

**Comment by sixhills** [comment]
Perhaps a disadvantage in enabling logging is that the keepalive messages are logged every 30 seconds at info level:

```
time="2020-08-17T14:34:08Z" level=info msg="[DEBUG] POST https://cloud.shellhub.io:443/api/devices/auth"
time="2020-08-17T14:34:38Z" level=info msg="[DEBUG] POST https://cloud.shellhub.io:443/api/devices/auth"
```

Connection failures are also logged at info level:

```
time="2020-08-17T14:02:14Z" level=info msg="[ERR] GET https://cloud.shellhub.io:443/info request failed: Get https://cloud.shellhub.io:443/info: dial tcp: lookup cloud.shellhub.io on 192.168.11.111:53: no such host"
time="2020-08-17T14:02:14Z" level=info msg="[DEBUG] GET https://cloud.shellhub.io:443/info: retrying in 4s (2147483645 left)"
```
and I can't see a way of logging failure messages while suppressing keepalive messages.  But that's probably my inexperience with Go.

**Comment by otavio** [comment]
No, I think it should log the failure as well. Maybe we could change the retry to every minute or five minutes, it'd not hurt. We just need to make sure it connects automatically if the connection is ever available.

@gustavosbarreto do you agree?

**Comment by gustavosbarreto** [comment]
I agree

**Comment by sixhills** [comment]
I am a little unclear about what is agreed,  I think it is agreed that the retryable http client should continue to be used and that http logging should be enabled so that failure to connect can be logged.

If http logging is enabled, a consequence of doing this is that keepalive messages will be logged every 30 seconds and quickly fill up the log.  Is that acceptable?

**Comment by otavio** [comment]
If user is concerned about log file limit, it should be adjusted on the hosting system. It can be adjusted on the Docker daemon or journalctl for example.

I am fine in increasing the retry to 1 minute to reduce the amount of logging and we might add an option later to adjust this as well if desired.

**Comment by gustavosbarreto** [comment]
> In the event of a name resolution failure, timeout or "connection refused", the agent appears to hang on initial startup without providing any error message.

 I can't reproduce the problem locally. Can you provide more info?

**Comment by sixhills** [comment]
@gustavosbarreto A simple way of reproducing the problem is to start the agent with the "docker run" command, specifying a non-existent host for SERVER_ADDRESS.  Or switch off name resolution or Internet access.   On observing the hang, I built a local agent with logging enabled and saw the "no such host" and retry messages logged earlier in this thread.
