### ISSUE TITLE
Record login activity to utmp when a pty session is created

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#317]
Most of unix login systems record login activity to utmp when a pty session is created.
The commands like `w` and `who` read from utmp to show the users currently logged into the system.

Suggested by @sixhills on Gitter chat channel.

**Comment by sixhills** [comment]
Also wtmp as a historical utmp.  I'm looking into doing this as an exercise, but new to Go and git, so steep learning curve!

**Comment by sixhills** [comment]
As a first step, I have implemented session start and session end logging into the agent.   My locally-built agent now logs, when a session starts:

`time="2020-08-19T16:21:29Z" level=info msg="Session started" localaddr="192.168.11.141:46724" pty=xterm remoteaddr="157.230.203.130:443" user=pi`

and, when a session ends:

`time="2020-08-19T16:32:36Z" level=info msg="Session ended" localaddr="192.168.11.141:46724" pty=xterm remoteaddr="157.230.203.130:443" user=pi`

This satisfies my personal requirement that there should be a record of inbound connections.

I want to implement utmp updating but wondered if this logging would be a useful addition by itself?

**Comment by otavio** [comment]
@sixhills I think so; it is a great addition for sure. Also, it could be the begin of #184 as it is related.

**Comment by sixhills** [comment]
OK, thanks.  Small improvement to log the device:

`time="2020-08-19T18:42:46Z" level=info msg="Session ended" localaddr="192.168.11.141:56566" pty=/dev/pts/3 remoteaddr="157.230.203.130:443" user=pi
`

But it is curious that the agent always uses the names /dev/pts/0, 1, 2, ... even if these are already in use by other processes.

**Comment by otavio** [comment]
It is running inside Docker? if so, it's likely under a namespace.

**Comment by sixhills** [comment]
Yes, it is and that makes sense.  Sorry for silly questons!

**Comment by otavio** [comment]
No problem at all; it is nice you are contributing. Looking forward for the first PR :-)

**Comment by sixhills** [comment]
I've implemented utmp/wtmp logging within the Shellhub client.  There are a few issues to resolve with the Dockerized agent but it's working fine outside Docker.  The standard utilities (who, w, users, last) all report login sessions started by the agent. There's one Shellhub-code issue I'd welcome advice about. One of the fields in the utmp record is the pid. I'm writing to the utmp file from within agent/sshd/server.go and I don't know how to get the pid of the child process started by the agent, so I'm writing the agent's pid to the utmp file.  None of the utilities that read utmp seem to use the pid field, so this isn't a major issue but it would be good to use the child's pid if it's available.

**Comment by otavio** [comment]
@sixhills, great news! Have you prepared the PR? So we could see what you are proposing, and then we can provide better feedback.

**Comment by sixhills** [comment]
@otavio Thanks. I'll do a PR in the next few days but I'd like to resolve the Docker issues first.

**Comment by sixhills** [comment]
I've found a more serious issue.  My code uses standard glibc functions to write to utmp and wtmp.  These functions aren't implemented in the Alpine base used for the agent Docker container, so my code won't work in the Shellhub Docker environment. I'll do a PR for info and feedback but the code may not be suitable for the project (although it's fine for me, running outside Docker) .

**Comment by otavio** [comment]
Indeed, I was not aware of this issue @sixhills. However, we may have an [option](https://skarnet.org/software/utmps/) here. It is [supported](https://pkgs.alpinelinux.org/package/edge/main/armhf/utmps) by Alpine and we could put that inside the image to allow it to manage this part.
