### ISSUE TITLE
Unable to SSH into a device using Public Key

### ISSUE THREAD

**Issue by geanceretta** [shellhub-io/shellhub#3183]
### Description

Dear Shellhub developers,

We at InoBram use Shellhub to SSH into our devices using a Public Key that matches the device hostname.

Since October 18, we are unable to login using the public key added on Shellhub.

Is there any changes related to this topic in the Shellhub behavior?

We add the public key through API, but even trough the key added via Shellhub Website we were unnable to SSH. I'm adding a ssh -vvv output. Thanks.

[ssh-vvv-output.log](https://github.com/shellhub-io/shellhub/files/13060998/ssh-vvv-output.log)

### Edition

Community

### Version

Current version at shell.inobram.com.br

**Comment by otavio** [comment]
As discussed privately, the issue has been fixed in your server.
