### ISSUE TITLE
cloud.shellhub.io Error: No such container: 

### ISSUE THREAD

**Issue by lapkritinis** [shellhub-io/shellhub#3191]
### Description

I just registered for cloud.shellhub.io and went through initial setup steps.
It did offered me to run curl -sSf "https://cloud.shellhub.io/install.sh?tenant_id=adfd49b6-REDACTED" | sh

I see that docker container runs, but in the log file all I see is:
2023-10-23 21:45:38 time="2023-10-23T18:45:38Z" level=warning msg="Error: No such container: "

What did I miss?

### Edition

Cloud

### Version

v0.13.0-rc.3

**Comment by gustavosbarreto** [comment]
Please paste the output of the following commands:

* `docker info`
* `docker inspect shellhub`
* `docker logs shellhub`

**Comment by lapkritinis** [comment]
Client:
 Version:    24.0.5
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     /Users/username/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     /Users/username/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/username/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/username/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/username/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/username/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/username/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /Users/username/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 3c369add-3976-4df8-83a7-2ef85aec6290
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

[
    {
        "Id": "a623d044bf328316f13a5eb1f7a1d482b88aeec8a3e68298f0149e206a026c59",
        "Created": "2023-10-23T18:43:03.326480179Z",
        "Path": "/bin/agent",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-10-23T18:45:38.463861958Z",
            "FinishedAt": "2023-10-23T18:45:38.496627916Z"
        },
        "Image": "sha256:7027fc8da4183e58111fdffe7e2d6d0db372f89af2bcfc49e7525b653720678e",
        "ResolvConfPath": "/host_mnt/private/var/run/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a623d044bf328316f13a5eb1f7a1d482b88aeec8a3e68298f0149e206a026c59/hostname",
        "HostsPath": "/var/lib/docker/containers/a623d044bf328316f13a5eb1f7a1d482b88aeec8a3e68298f0149e206a026c59/hosts",
        "LogPath": "/var/lib/docker/containers/a623d044bf328316f13a5eb1f7a1d482b88aeec8a3e68298f0149e206a026c59/a623d044bf328316f13a5eb1f7a1d482b88aeec8a3e68298f0149e206a026c59-json.log",
        "Name": "/shellhub",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/resolv.conf:/etc/resolv.conf",
                "/var/run:/var/run",
                "/var/log:/var/log",
                "/:/host",
                "/dev:/dev",
                "/run/host-services/docker.proxy.sock:/var/run/docker.sock",
                "/host_mnt/private/etc/passwd:/etc/passwd",
                "/host_mnt/private/etc/group:/etc/group"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                19,
                208
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "host",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/f4ad602b7c72fe2d118877c7696a0ccf6a2eeee6a863733d0ac5a1dfe6845ddc-init/diff:/var/lib/docker/overlay2/5ba0c5fa48c749a570a4c1fd6706167af367a3238b702db3957189312a68468d/diff:/var/lib/docker/overlay2/832398467ee08004f1bbf7d5de828ea620ca2b360fe01ee6b0e077da729e446c/diff:/var/lib/docker/overlay2/04582844f40a4110ae949ccc6b47a14411b064595e80b5f1082bcaaaf929d316/diff:/var/lib/docker/overlay2/c4bff2489a1519a3847d2091a41fb2116cbac160629257c1e4d4e81c34ba8685/diff:/var/lib/docker/overlay2/e6c0b64f0cd62c51e54ae5c7ae0007add508fa733d6523997c7543dc051482dc/diff:/var/lib/docker/overlay2/e3678d3546b12200325d7b6b237aa88777779d37eedb59770127f2590690abe9/diff",
                "MergedDir": "/var/lib/docker/overlay2/f4ad602b7c72fe2d118877c7696a0ccf6a2eeee6a863733d0ac5a1dfe6845ddc/merged",
                "UpperDir": "/var/lib/docker/overlay2/f4ad602b7c72fe2d118877c7696a0ccf6a2eeee6a863733d0ac5a1dfe6845ddc/diff",
                "WorkDir": "/var/lib/docker/overlay2/f4ad602b7c72fe2d118877c7696a0ccf6a2eeee6a863733d0ac5a1dfe6845ddc/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/dev",
                "Destination": "/dev",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/private/etc/group",
                "Destination": "/etc/group",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/private/etc/passwd",
                "Destination": "/etc/passwd",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/resolv.conf",
                "Destination": "/etc/resolv.conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/",
                "Destination": "/host",
                "Mode": "",
                "RW": true,
                "Propagation": "rslave"
            },
            {
                "Type": "bind",
                "Source": "/var/log",
                "Destination": "/var/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run",
                "Destination": "/var/run",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/run/host-services/docker.proxy.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "docker-desktop",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SHELLHUB_SERVER_ADDRESS=https://cloud.shellhub.io:443",
                "SHELLHUB_PRIVATE_KEY=/host/etc/shellhub.key",
                "SHELLHUB_TENANT_ID=adfd49b6-REDACTED",
                "SHELLHUB_LOG_LEVEL=debug",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "shellhubio/agent",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/agent"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ddce772de5a39134b6ffb6c3303b8ab22ca60d3c6345e297b0638501c5c7c1e1",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "67c9d46d103e9d218f609b845ed7ae2b63f1d2b304a1723f0d1e707e11e23d37",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

time="2023-10-23T18:43:03Z" level=warning msg="Error: No such container: "
time="2023-10-23T18:45:38Z" level=warning msg="Error: No such container: "

**Comment by gustavosbarreto** [comment]
@lapkritinis Are you using MacOS?

**Comment by lapkritinis** [comment]
Yea, I am. Not supported?

**Comment by gustavosbarreto** [comment]
> Yea, I am. Not supported?

MacOS is not yet supported

**Comment by Vercety87** [comment]
Hi, got the same error on Debian :(

`Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 53
  Running: 45
  Paused: 0
  Stopped: 8
 Images: 98
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-26-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 17.56GiB
 Name: debian-docker
 ID: GCBU:7OC7:PVMV:WRV4:CMDK:FNZ7:GLWI:DXMY:ZKSF:DDS4:GHHY:Y6TJ
 Docker Root Dir: /mnt/sda/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 16.22.19.0/16, Size: 24
   Base: 22.16.19.0/16, Size: 24`


`[
    {
        "Id": "15dfec306586b3b832425f8c5c4cf79ad78b511cb7cda52b284f745a87ce3a3e",
        "Created": "2023-11-29T14:36:41.157737473Z",
        "Path": "/bin/agent",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-11-29T14:36:41.286046926Z",
            "FinishedAt": "2023-11-29T14:36:41.321919565Z"
        },
        "Image": "sha256:e7741ff94f748a3ca84038511b17ffd555da3abccd51d656152779ab643f16f4",
        "ResolvConfPath": "/etc/resolv.conf",
        "HostnamePath": "/mnt/sda/docker/containers/15dfec306586b3b832425f8c5c4cf79ad78b511cb7cda52b284f745a87ce3a3e/hostname",
        "HostsPath": "/mnt/sda/docker/containers/15dfec306586b3b832425f8c5c4cf79ad78b511cb7cda52b284f745a87ce3a3e/hosts",
        "LogPath": "/mnt/sda/docker/containers/15dfec306586b3b832425f8c5c4cf79ad78b511cb7cda52b284f745a87ce3a3e/15dfec306586b3b832425f8c5c4cf79ad78b511cb7cda52b284f745a87ce3a3e-json.log",
        "Name": "/shellhub",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/:/host",
                "/dev:/dev",
                "/var/run/docker.sock:/var/run/docker.sock",
                "/etc/passwd:/etc/passwd",
                "/etc/group:/etc/group",
                "/etc/resolv.conf:/etc/resolv.conf",
                "/var/run:/var/run",
                "/var/log:/var/log"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                42,
                135
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "host",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/sda/docker/overlay2/cc11660c66816d7eee3c762b06f91edb30080c630f1dcebe6fa16f947ed9e803-init/diff:/mnt/sda/docker/overlay2/cbb9c18036f19768b3ce42efcf2db1298bd10824e239a0b12878d2f8c251fb6c/diff:/mnt/sda/docker/overlay2/cba2764bba4878cbb18e82b624370215cf8f2101cb936a465ac838dda8ed1f56/diff:/mnt/sda/docker/overlay2/5eb6b42c39e11f1e2b2bbf5cb481bf4e0de562b99a4a219324886a75ebbd5098/diff:/mnt/sda/docker/overlay2/9feaf248c2b1e424cd8a06ef0e95323aaaebf210fd2d53a27540622298189dd3/diff:/mnt/sda/docker/overlay2/7c576eae92bbb87ceb4ff81a42d73f8b1e29e60c96427b0b5f422f86ef4a2fa6/diff:/mnt/sda/docker/overlay2/3b353c391bf2cb166564f65c928d2e3492ca9703416c7268155c2de9568b1925/diff:/mnt/sda/docker/overlay2/858daf4351406976d2fc9be09edd8ed05bc8768a74bffe55f60259cf8ea05bc8/diff",
                "MergedDir": "/mnt/sda/docker/overlay2/cc11660c66816d7eee3c762b06f91edb30080c630f1dcebe6fa16f947ed9e803/merged",
                "UpperDir": "/mnt/sda/docker/overlay2/cc11660c66816d7eee3c762b06f91edb30080c630f1dcebe6fa16f947ed9e803/diff",
                "WorkDir": "/mnt/sda/docker/overlay2/cc11660c66816d7eee3c762b06f91edb30080c630f1dcebe6fa16f947ed9e803/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/log",
                "Destination": "/var/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/",
                "Destination": "/host",
                "Mode": "",
                "RW": true,
                "Propagation": "rslave"
            },
            {
                "Type": "bind",
                "Source": "/dev",
                "Destination": "/dev",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/passwd",
                "Destination": "/etc/passwd",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/group",
                "Destination": "/etc/group",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/resolv.conf",
                "Destination": "/etc/resolv.conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run",
                "Destination": "/var/run",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "debian-docker",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SHELLHUB_TENANT_ID=7d0fd504-6e05-496c-9d14-732d83d22096",
                "SHELLHUB_SERVER_ADDRESS=http://192.168.50.249:80",
                "SHELLHUB_PRIVATE_KEY=/host/etc/shellhub.key",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "shellhubio/agent:v0.13.1",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/bin/agent"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "36b9c7f3f01a159ab8adcce5539c3c73459a073e3425201a3248e7612878420a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "20a4380d7da1f3337f412e14e8378eaf67733b0bd7a7bc9b17803547c8e0ed37",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]`

`root@debian-docker:/mnt/sda/containers/sshwifty# docker logs shellhubtime="2023-11-29T14:36:41Z" level=info msg="Setting log level" log_level=info
time="2023-11-29T14:36:41Z" level=warning msg="Error: No such container: "`

**Comment by otavio** [comment]
@gustavosbarreto please take a look above.

**Comment by Vercety87** [comment]
Just upgraded to 0.13.5 but same problem

**Comment by FirYuen** [comment]
This problem eccours when /var/lib/docker is binded from another folder

**Comment by FirYuen** [comment]
> This problem eccours when /var/lib/docker is binded from another folder
for example
```
/data/docker /var/lib/docker auto defaults,nofail,nobootwait,bind 0 2
/data/log /var/log auto defaults,nofail,nobootwait,bind 0 2
```
result  
```
 re := regexp.MustCompile(`\d+\s\d+\s\d+:\d+\s.+docker/overlay2?.+([0-9a-f]{64})/`) 
```
won't work as expected

**Comment by FirYuen** [comment]
> > This problem eccours when /var/lib/docker is binded from another folder
> > for example
> 
> ```
> /data/docker /var/lib/docker auto defaults,nofail,nobootwait,bind 0 2
> /data/log /var/log auto defaults,nofail,nobootwait,bind 0 2
> ```
> 
> result
> 
> ```
>  re := regexp.MustCompile(`\d+\s\d+\s\d+:\d+\s/var/.+docker/?.+([0-9a-f]{64})/`)
> ```
> 
> won't work as expected

i would like to recommand change this regex to 
```
re := regexp.MustCompile(`\d+\s\d+\s\d+:\d+\s.+containers/?.+([0-9a-f]{64})/hostname`)
```
since we our docker is raned in `host` netmode.
I have already did some tests, works as a charming.

**Comment by otavio** [comment]
Ohhh nice you did figure it out. It would be great if you can prepare a pull request fixing it.
