### ISSUE TITLE
SSH Tunneling test returns normal response even with incorrect password

### ISSUE THREAD

**Issue by civilizeddev** [shellhub-io/shellhub#3240]
In DBeaver, instead of connecting remotely, there's a button to simply test the creation of an SSH Tunnel. For other typical SSH implementations, if you input the wrong password at this time, an error is returned. But with shellhub, even if you don't enter the password or enter it incorrectly, a normal response is displayed. This can give the wrong signal to the user.

![image](https://github.com/shellhub-io/shellhub/assets/15084045/80d601ea-fd1f-40cb-8cc3-29e64118d841)

_Originally posted by @civilizeddev in https://github.com/shellhub-io/shellhub/issues/3233#issuecomment-1789993330_

### Edition

Community

### Version

v0.13.1 (+https://github.com/shellhub-io/shellhub/commit/059572f54a1569f11affff0609e363c4c3368941)

**Comment by civilizeddev** [comment]
### Logs (shellhub-ssh)

```
level=trace msg="trying to use password authentication" sshid=ubuntu@(redacted SSHID)
level=info msg="using password authentication method to connect the client to agent" sshid=ubuntu@(redacted SSHID)
```

**Comment by civilizeddev** [comment]
### Logs (shellhub-ssh)

If you proceed with port forwarding with the wrong password, this is what happens.

```
level=trace msg="trying to use password authentication" sshid=ubuntu@(redacted)
level=info msg="using password authentication method to connect the client to agent" sshid=ubuntu@(redacted)
level=info msg="handling direct-tcpip channel" sshid=(redacted) username=ubuntu
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xa51fd7]

goroutine 85 [running]:
github.com/shellhub-io/shellhub/ssh/session.(*Session).NewClientConnWithDeadline(0xc00022a6e0, 0xc0001da680)
    github.com/shellhub-io/shellhub/ssh/session/session.go:233 +0x3f7
github.com/shellhub-io/shellhub/ssh/server.NewServer.TunnelDefaultDirectTCPIPHandler.func6(0xc0000f90e0, 0xc000010480?, {0xe36658, 0xc0001300c0}, {0xe3c5a0, 0xc000010048})
    github.com/shellhub-io/shellhub/ssh/server/channels/tcpip.go:122 +0xe05
created by github.com/gliderlabs/ssh.(*Server).HandleConn in goroutine 47
    github.com/gliderlabs/ssh@v0.3.5/server.go:305 +0x52b
```

**Comment by henrybarreto** [comment]
Sorry, I think I didn't get it because I was using a public key for authentication.

I have forced a push with a small modification to check if it solves that panic problem.

I will test here

**Comment by henrybarreto** [comment]
Okay, I seam to be solved. Could you, please, test it again?

**Comment by civilizeddev** [comment]
Now, a panic does not occur due to a password error.

```
level=trace msg="trying to use password authentication" sshid=ubuntu@(redacted)
level=info msg="using password authentication method to connect the client to agent" sshid=ubuntu@(redacted)
level=info msg="handling direct-tcpip channel" sshid=(redacted) username=ubuntu
level=error msg="Error when trying to create the client's connection" error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain" session=(redacted)
level=error msg="failed creating agent connection" dest_addr=(redacted) dest_port=5432 error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain" origin_addr=26587 origin_port= sshid=(redacted) username=ubuntu
```

However, it still responds as normal when the test ssh tunnel is executed.

**Comment by henrybarreto** [comment]
> Now, a panic does not occur due to a password error.
> 
> ```
> level=trace msg="trying to use password authentication" sshid=ubuntu@(redacted)
> level=info msg="using password authentication method to connect the client to agent" sshid=ubuntu@(redacted)
> level=info msg="handling direct-tcpip channel" sshid=(redacted) username=ubuntu
> level=error msg="Error when trying to create the client's connection" error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain" session=(redacted)
> level=error msg="failed creating agent connection" dest_addr=(redacted) dest_port=5432 error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain" origin_addr=26587 origin_port= sshid=(redacted) username=ubuntu
> ```
> 
> However, it still responds as normal when the test ssh tunnel is executed.
> 
> ```
> level=trace msg="trying to use password authentication" sshid=ubuntu@(redacted)
> level=info msg="using password authentication method to connect the client to agent" sshid=ubuntu@(redacted)
> ```

I think that the second problem is a bit more complicated to be solved. I will verify what we can do.

**Comment by henrybarreto** [comment]
Hi, @civilizeddev.

Thank you for your patience.

This is a normal behavior of ShellHub. Before user connect to the device itself, they connect to our gateway, what validates some information and redirect the data to the device.

The DBeaver tests only this first step, as a result, it is always successful.
