### ISSUE TITLE
Is it possible to use SSH tunneling?

### ISSUE THREAD

**Issue by ironerumi** [shellhub-io/shellhub#328]
Hi, thanks a lot for the awesome project!

I'm able to SSH into my ubuntu box, however, when I use SSH to bind my port to remote port.
The following error occurs.
`channel 2: open failed: unknown channel type: unsupported channel type`
 Is it possible to use SSH tunneling?

Many thanks!

**Comment by adechassey** [comment]
Hi guys,
Any plans to implement this feature in the near future?
Would be very nice to have a kind of switch equivalent to `AllowTcpForwarding yes` of OpenSSH :)
