### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#3290]
### Discussed in https://github.com/shellhub-io/shellhub/discussions/3287

<div type='discussions-op-text'>

<sup>Originally posted by **Cahoots2843** November 13, 2023</sup>
Hello,

How can I delete my account on https://cloud.shellhub.io/ ? 

I tried to "Delete Namespace" but, I keep in a endless loading.

![Screenshot 2023-11-13 at 18 34 54](https://github.com/shellhub-io/shellhub/assets/40402385/01e8bd91-3f5e-413f-9616-f8e36c01dd16)

How can I do that? I didn't find any email to solve that.</div>

**Comment by heiytor** [comment]
fixed in #3304
