### ISSUE TITLE
HTTPS certificate not auto renew after a month

### ISSUE THREAD

**Issue by prakharnigam** [shellhub-io/shellhub#3294]
### Description

I have been using Shellhub for the past month, but after a month of use with HTTPS ENABLED. 
I am facing an issue while renewing my HTTPS certificate. Check attached images.

![image](https://github.com/shellhub-io/shellhub/assets/10355945/ef062ea3-1d40-4df9-9ce3-2933dd032a07)

### Edition

Community

### Version

0.12.4

**Comment by otavio** [comment]
Please upgrade to 0.13.4 and see if it helps.

**Comment by gustavosbarreto** [comment]
This issue has been successfully resolved by commit ecc24aee83427d299d2e83c4ab0b90cf72b7c87a. The fix is now available in the latest release (`v0.14.0`).
