### ISSUE TITLE
ESC is not captured for the web terminal

### ISSUE THREAD

**Issue by zhanglongqi** [shellhub-io/shellhub#330]
if we use vim in the web terminal, we will stuck there and can not exit vim.

**Comment by gustavosbarreto** [comment]
@zhanglongqi  I can't reproduce the problem locally. Can you provide more info?

**Comment by zhanglongqi** [comment]
1. login one of your Linux device through ssh on web terminal
2. use vim to edit some file
I have tried with chrome 84 and firefox 80 with addon disabled. they all have the same issue.

**Comment by gustavosbarreto** [comment]
> 1. login one of your Linux device through ssh on web terminal
> 2. use vim to edit some file
> 
> I have tried with chrome 84 and firefox 80 with addon disabled. they all have the same issue.

Which operating system are you using on client side?

**Comment by zhanglongqi** [comment]
My remote: 

`Raspbian GNU/Linux 10 (buster)` 

`Linux 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux`

```shell
LANG=en_SG.UTF-8
LANGUAGE=en_SG.UTF-8
LC_CTYPE="en_SG.UTF-8"
LC_NUMERIC="en_SG.UTF-8"
LC_TIME="en_SG.UTF-8"
LC_COLLATE="en_SG.UTF-8"
LC_MONETARY="en_SG.UTF-8"
LC_MESSAGES="en_SG.UTF-8"
LC_PAPER="en_SG.UTF-8"
LC_NAME="en_SG.UTF-8"
LC_ADDRESS="en_SG.UTF-8"
LC_TELEPHONE="en_SG.UTF-8"
LC_MEASUREMENT="en_SG.UTF-8"
LC_IDENTIFICATION="en_SG.UTF-8"
LC_ALL=en_SG.UTF-8
```

My local:
`18.04.5 LTS (Bionic Beaver)`
`Linux 5.4.0-44-generic #48~18.04.1-Ubuntu SMP Wed Aug 12 10:16:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
```shell
LANG=en_SG.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
