### ISSUE TITLE
Port forwarding failure on password authentication

### ISSUE THREAD

**Issue by CloudCray** [shellhub-io/shellhub#3451]
### Description

When attempting to make a request over a forwarded port through shellhub, I receive an error.

**Example**:

- I have a machine, WEB, running on a remote network (192.168.1.55), hosting a webserver on port 8000.
- I have a gateway server, GATEWAY, running the shellhub agent (192.168.1.230) on the same network
- I want to forward traffic on my local port, 8055, to WEB:8000, so I can run make requests to WEB without opening a new session every time.
- I am using password authentication for all ssh connections

### SSH connection to GATEWAY succeeds

I can ssh into GATEWAY no problem, and once I'm ssh'd in, I can connect to WEB no problem.

```
ssh user@my-namespace.GATEWAY@cloud.shellhub.io  curl 192.168.1.55:8000/my-endpoint
# 200: Success
```

Same thing if I'm on VPN and SSH into GATEWAY directly
```
ssh user@192.168.1.230 curl 192.168.1.55:8000/my-endpoint
# 200: Success
```

### Port Forwarding Succeeds when open on VPN with IP address
If I connect via VPN and attempt to port forward through vanilla SSH, I can access WEB from my local machine.
```
ssh -L 8055:192.168.1.55:8000 user@192.168.1.230 -v -v -v -N
```

Then in a separate terminal, I can run a successful http request on the locally bound port
```
curl 0.0.0.0:8055/my-endpoint
# 200: Success
```

The log from my successful connection reads:
```
debug1: Connection to port 8055 forwarding to 192.168.1.55 port 8000 requested.
debug2: fd 6 setting TCP_NODELAY
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 2: new [direct-tcpip]
debug3: send packet: type 90
debug3: receive packet: type 91
debug2: channel 2: open confirm rwindow 2097152 rmax 32768
debug3: receive packet: type 96
debug2: channel 2: rcvd eof
debug2: channel 2: output open -> drain
debug2: channel 2: obuf empty
debug2: chan_shutdown_write: channel 2: (i0 o1 sock 6 wfd 6 efd -1 [closed])
debug2: channel 2: output drain -> closed
debug2: channel 2: read failed rfd 6 maxlen 32768: Broken pipe
debug2: channel 2: read failed
debug2: chan_shutdown_read: channel 2: (i0 o3 sock 6 wfd 6 efd -1 [closed])
debug2: channel 2: input open -> drain
debug2: channel 2: ibuf empty
debug2: channel 2: send eof
debug3: send packet: type 96
debug2: channel 2: input drain -> closed
debug2: channel 2: send close
debug3: send packet: type 97
debug3: channel 2: will not send data after close
debug3: receive packet: type 97
debug2: channel 2: rcvd close
debug3: channel 2: will not send data after close
debug2: channel 2: is dead
debug2: channel 2: garbage collecting
debug1: channel 2: free: direct-tcpip: listening port 8055 for 192.168.1.55 port 8000, connect from 127.0.0.1 port 36794 to 127.0.0.1 port 8055, nchannels 3
debug3: channel 2: status: The following connections are open:
  #2 direct-tcpip: listening port 8055 for 192.168.1.55 port 8000, connect from 127.0.0.1 port 36794 to 127.0.0.1 port 8055 (t4 r0 i3/0 o3/0 e[closed]/0 fd 6/6/-1 sock 6 cc -1 io 0x00/0x00)
```

### Port Forwarding Fails if port is forwarded through Shellhub

However, when I try to port forward through shellhub, the connection seems to succeed, but fails as soon as any traffic attempts to go over the connection.

```
ssh -L 8055:192.168.1.55:8000 user@my-namespace.GATEWAY@cloud.shellhub.io -v -v -v -N
```

Then in a separate terminal,
```
curl 0.0.0.0:8055/my-endpoint
```

Curl gives me this error:
`curl: (56) Recv failure: Connection reset by peer`

Here's the log of what happens in the port-forward session:
```
debug1: Connection to port 8055 forwarding to 192.168.1.55 port 8000 requested.
debug2: fd 6 setting TCP_NODELAY
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 2: new [direct-tcpip]
debug3: send packet: type 90
debug3: receive packet: type 92
channel 2: open failed: connect failed: failed to create session
debug2: channel 2: zombie
debug2: channel 2: garbage collecting
debug1: channel 2: free: direct-tcpip: listening port 8055 for 192.168.1.55 port 8000, connect from 127.0.0.1 port 56466 to 127.0.0.1 port 8055, nchannels 3
debug3: channel 2: status: The following connections are open:
```

I am planning on deploying a network with a similar setup at a different location, where I will NOT have VPN access. I am hoping to have this resolved before then, as port-forwarding would make accessing similar WEB devices much simpler.

Any support would be greatly appreciated, thank you.

### Edition

Cloud

### Version

v0.14.0

**Comment by henrybarreto** [comment]
Hi, @CloudCray. Thank you for the report.

 We are verifying what is happening. As soon as we have feedback, you will be informed.

**Comment by henrybarreto** [comment]
Hi, @CloudCray. 

We have deployed this fix on the Cloud. Could you test it again?
