### ISSUE TITLE
Closing a connection from the close connections page doesn't work

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3469]
### Description

When you have an SSH session open, whether it's from a terminal or the web UI, clicking on close session from another tab doesn't do anything. See the screen recording below

https://github.com/shellhub-io/shellhub/assets/4641317/054248d4-8d54-4e52-a83e-94d1d37039b1

### Edition

Community

### Version

0.13.1

**Comment by henrybarreto** [comment]
Hi, @Seluj78. 

Thank you for your report.

We have fixed this bug in `v0.14.1`.

If you encounter any further issues or have additional feedback, please don't hesitate to reach out to us. We appreciate your diligence in reporting bugs and helping us improve our product.

**Comment by Seluj78** [comment]
Alright thank you very much. When will `0.14.1` become the next standard version ?

**Comment by henrybarreto** [comment]
It has just been set as our latest version.

**Comment by gustavosbarreto** [comment]
Closing this as resolved.

**Comment by Seluj78** [comment]
Can confirm it is fixed as of `0.14.1`
