### ISSUE TITLE
gateway: reports "Broken header" when using nginx ssl reverse proxy

### ISSUE THREAD

**Issue by sixhills** [shellhub-io/shellhub#347]
Shellhub v0.3.7 with nginx/1.14.2

I have a self-hosted Shellhub server started with the standard docker-compose method, listening on external port 8090, and it works fine.  I've set up an ssl nginx reverse proxy (not dockerized) in front of the ShellHub server listening on port 8095, passing data to the Shellhub gateway on port 8090.  HTTPS access via the proxy to the Shellhub server works fine with SHELLHUB_PROXY=false, showing that the proxy works for HTTP.

After setting SHELLHUB_PROXY=true and restarting Shellhub with docker-compose, every access via the proxy fails with a "broken header" error.  An example is:

```
gateway_1_f5da0b62b647 | Host: localhost:8090
gateway_1_f5da0b62b647 | Connection: close
gateway_1_f5da0b62b647 | User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
gateway_1_f5da0b62b647 | Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
gateway_1_f5da0b62b647 | Accept-Language: en-GB,en;q=0.5
gateway_1_f5da0b62b647 | Accept-Encoding: gzip, deflate, br
gateway_1_f5da0b62b647 | DNT: 1
gateway_1_f5da0b62b647 | Upgrade-Insecure-Requests: 1
gateway_1_f5da0b62b647 | Cache-Control: max-age=0
gateway_1_f5da0b62b647 |
gateway_1_f5da0b62b647 | " while reading PROXY protocol, client: 172.22.0.1, server: 0.0.0.0:80

```

[The example above has been edited: the first example posted was from a Shellhub client accessing the server without going via the proxy.  The edited example is from an attempt to access the web interface from a standard web client through the proxy.]

My nginx reverse proxy definition is:

```
server {
  listen        8095 ssl;

  ssl_certificate     /etc/letsencrypt/live/domain-name/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domain-name/privkey.pem;

  location / {
    proxy_pass  http://localhost:8090;
  }
}

```

The Shellhub .env file is:

```
SHELLHUB_VERSION=v0.3.7
SHELLHUB_HTTP_PORT=8090
SHELLHUB_SSH_PORT=9822
SHELLHUB_PROXY=true
SHELLHUB_HOSTED=false
```

Also reported by @jcampos79_gitlab on the Gitter channel.

**Comment by gustavosbarreto** [comment]
> gateway_1_f5da0b62b647 | " while reading PROXY protocol, client: 172.22.0.1, server: 0.0.0.0:80

It looks like the gateway is expecting a proxy connection from the ssl reverse proxy

> My nginx reverse proxy definition is:

You need to enable to PROXY protocol. Add the `proxy_protocol` directive within the server section of nginx conf:

```
server {
  listen        8095 ssl;
  proxy_protocol on;

  ssl_certificate     /etc/letsencrypt/live/domain-name/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domain-name/privkey.pem;

  location / {
    proxy_pass  http://localhost:8090;
  }
}
```

**Comment by sixhills** [comment]
Thanks for the advice.  I've made that change but nginx then fails to start:

`nginx[3322]: nginx: [emerg] "proxy_protocol" directive is not allowed here in /etc/nginx/sites-enabled/shellhub.conf:3`

**Comment by gustavosbarreto** [comment]
> Thanks for the advice. I've made that change but nginx then fails to start:
> 
> `nginx[3322]: nginx: [emerg] "proxy_protocol" directive is not allowed here in /etc/nginx/sites-enabled/shellhub.conf:3`

To use 'proxy_protocol' you need to use a _stream server_ instead of _http server_. 

Does this works for you?

`/etc/nginx/nginx.conf`:

```
worker_processes  1;

events {
    worker_connections  1024;
}

stream {
    upstream shellhub {
        least_conn;
        server localhost:80;
    }

    server {
        listen 8082 ssl;
        proxy_protocol on;

        ssl_certificate     /etc/letsencrypt/live/domain-name/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/domain-name/privkey.pem;

        proxy_pass  http_backend;
    }
}
```

**Comment by sixhills** [comment]
It works!  I just had to insert:

`load_module /usr/lib/nginx/modules/ngx_stream_module.so;
`

at the start of the file.

I thought there was something wrong with my nginx config but wasn't sure what it was. It would be very helpful to publish that example conf file in the "Production Deployment" section of the manual.

Thanks again for the excellent support!

**Comment by otavio** [comment]
@sixhills maybe you could prepare a PR for the docs?

**Comment by sixhills** [comment]
OK - I'll have a go.

**Comment by gustavosbarreto** [comment]
I think most of users don't need to enable proxy protocol to deploy a simple SSLproxy in front of ShellHub gateway.
The proxy protocol would only be required if has a Layer 4 load balancer in front of ShellHub gateway.

I'll update the docs explaining when `SHELLHUB_PROXY` should be enable or not.

**Comment by gustavosbarreto** [comment]
Docs updated: https://docs.shellhub.io/admin-manual/production-deployment/

**Comment by gustavosbarreto** [comment]
Here is a step by step how to achieve a SSL proxy in-front of ShellHub using `docker-nginx-auto-ssl` container:

1) Create a `docker-compose.override.yml`:

```
version: '3.7'

services:
  nginx:
    image: valian/docker-nginx-auto-ssl:1.2.0
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    environment:
      ALLOWED_DOMAINS: '${SHELLHUB_DOMAIN}'
      SITES: '${SHELLHUB_DOMAIN}=gateway:80'
```

2) Unexpose gateway port on host network by setting `SHELLHUB_HTTP_PORT=0` in `.env` file.
3) Set `SHELLHUB_DOMAIN` for desired domain in `.env` file. e.g. `SHELLHUB_DOMAIN=example.com`

What do you think about adding this step by step to documentation?

**Comment by sixhills** [comment]
I've just tried that method and it works perfectly.  Impressive!  It's simpler than using proxy_protocol and automatically obtaining an SSL certificate is a nice touch.  I'd be happy to update the documentation with this method if it would help.  Is the "material for mkdocs" manual held on github?

I've found a minor issue with the proxy_protocol method: the curl command provided by the server correctly specifies https and the correct proxy port but the "docker run" command within the install.sh script specifies "http" instead of "https":

`-e SERVER_ADDRESS=http://FQDN:8095 \`

**Comment by sixhills** [comment]
There may be a timing issue.  Sometimes, the valian nginx container fails to start with:

`2020/08/28 15:00:26 [emerg] 1#1: host not found in upstream "gateway" in /etc/nginx/conf.d/fqdn.conf:18`

Adding "restart: on-failure" to the nginx definition fixes this, although there may be a better way.

**Comment by gustavosbarreto** [comment]
> Is the "material for mkdocs" manual held on github?

https://www.mkdocs.org/

Instructions to run docs on your machine:

```
cd shellhub-io.github.io
pip install -r requirements.txt
~/.local/bin/mkdocs serve
```

**Comment by sixhills** [comment]
Thanks for the link to the documentation.

**Comment by sixhills** [comment]
Using the valian proxy worked when I first used it but it's now failing when trying to register a device.
The API log on the server reports an EOF error:

`{"time":"2020-08-28T19:39:57.282522287Z","id":"","remote_ip":"client-IP-address","host":"api:8080","method":"POST","uri":"/api/devices/auth","user_agent":"Go-http-client/2.0","status":500,"error":"EOF","latency":16986455,"latency_human":"16.986455ms","bytes_in":646,"bytes_out":36}`

and this results in the nginx and gateway logs reporting:

`"POST /api/devices/auth HTTP/1.1" 500 36 "-" "Go-http-client/2.0"`

I don't think I've changed anything since it worked.

**Comment by gustavosbarreto** [comment]
> Using the valian proxy worked when I first used it but it's now failing when trying to register a device.
> The API log on the server reports an EOF error:
> 
> `{"time":"2020-08-28T19:39:57.282522287Z","id":"","remote_ip":"client-IP-address","host":"api:8080","method":"POST","uri":"/api/devices/auth","user_agent":"Go-http-client/2.0","status":500,"error":"EOF","latency":16986455,"latency_human":"16.986455ms","bytes_in":646,"bytes_out":36}`
> 
> and this results in the nginx and gateway logs reporting:
> 
> `"POST /api/devices/auth HTTP/1.1" 500 36 "-" "Go-http-client/2.0"`
> 
> I don't think I've changed anything since it worked.

This error didn't happen in my test instance (test.shellhub.io)

**Comment by sixhills** [comment]
I've found the cause of the 500 error.  I rebuilt the server containers and this generated a new tenant_id.  But my browser (Firefox) had cached the old tenant_id and I tried to register a device using this old tenant_id.  Using the correct tenant_id works.

I've confirmed that attempting to register a device with an invalid tenant_id always results in the api logging an "EOF" error and the gateway returning 500, whether or not an ssl proxy is used.  Should this be regarded as a bug?

So the valian container works very well as an ssl proxy.  I've made one change to put the certificate on the host to avoid it generating a new certificate on each build:

```
    volumes:
      - /etc/ssl_data:/etc/resty-auto-ssl
```

**Comment by otavio** [comment]
@sixhills 
> I've confirmed that attempting to register a device with an invalid tenant_id always results in the api logging an "EOF" error and the gateway returning 500, whether or not an ssl proxy is used. Should this be regarded as a bug?

Sure, this should be handled gracefully and ideally log something on the server side as well, so it is easier to find out the issue if someone face this scenario as well.

**Comment by sixhills** [comment]
There's a bug in my code (PR#329) that logs a "Connection established" message.  When the agent connects to cloud.shellhub.io, info.Endpoints.SSH in agent/main.go has 3 colon-separated fields, like:

`cloud.shellhub.io:443:22`

and my code assumes that there will always be 3 fields.  But when SHELLHUB_HTTP_PORT=0 for use with the ssl proxy, this has only 2 fields:

`cloud.shellhub.io:22`

and the code fails with "index out of range".  I have fixed the code locally so that it accepts both forms but I don't know whether it's best to fix it in agent/main.go or somewhere else.  I think I should stop suggesting code changes until I understand it better, as I don't want to cause you extra work.

**Comment by otavio** [comment]
Prepare a PR for it :-)

**Comment by gustavosbarreto** [comment]
@all-contributors please add @sixhills for code

**Comment by sixhills** [comment]
@gustavosbarreto Thanks for fixing this.  The revised code is much better than mine.

**Comment by otavio** [comment]
@sixhills is there anything open in this issue or we can close it?

**Comment by sixhills** [comment]
Please close it, thanks.

**Comment by glynhudson** [comment]
Unfortunately using the nginx `stream` [does not work](https://stackoverflow.com/questions/45227491/nginx-server-name-inside-stream-block-possible  ) with `server_name`. I need to be able to assign a domain name if possible to shellhub. Is there an nginx solution which works with shellhub on a sub domain?

I'm currently using the following nginx config which works fine for the web interface and I can register devices, however the terminal is blank:

```
server {

        listen 443 ssl http2;
        # Whitelist IP's
        include /etc/nginx/cloudflare-allow.conf;

        server_name shellhub.xxxxx.com;

        ssl_certificate /etc/nginx/ssl/site.crt;
        ssl_certificate_key /etc/nginx/ssl/site-key.pem;

        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 180m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        # add Strict-Transport-Security to prevent man in the middle attacks
        add_header Strict-Transport-Security "max-age=31536000";

        location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8999;

        }
```

**Comment by ichintu** [comment]
> > Thanks for the advice. I've made that change but nginx then fails to start:
> > `nginx[3322]: nginx: [emerg] "proxy_protocol" directive is not allowed here in /etc/nginx/sites-enabled/shellhub.conf:3`
> 
> To use 'proxy_protocol' you need to use a _stream server_ instead of _http server_.
> 
> Does this works for you?
> 
> `/etc/nginx/nginx.conf`:
> 
> ```
> worker_processes  1;
> 
> events {
>     worker_connections  1024;
> }
> 
> stream {
>     upstream shellhub {
>         least_conn;
>         server localhost:8090;
>     }
> 
>     server {
>         listen 8095 ssl;
>         proxy_protocol on;
> 
>         ssl_certificate     /etc/letsencrypt/live/domain-name/fullchain.pem;
>         ssl_certificate_key /etc/letsencrypt/live/domain-name/privkey.pem;
> 
>         proxy_pass  shellhub;
>     }
> }
> ```

How do you use Lets Encrypt with this setting?

**Comment by sixhills** [comment]
@ichintu This issue has been closed, so it's probably best to start a new issue or ask on the Gitter chat channel https://gitter.im/shellhub-io/community It's not clear what you're asking, so please provide more detail.
