### ISSUE TITLE
Device is offline after upgrade, reinstalling agent doesn't work

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3474]
### Description

I just upgraded shellhub from `0.13.1` to `0.14.1` following your procedure (make stop, checkout latest tag, make start).

When I arrived on the dashboard, first thing I noticed was the extreme slowness of the API. For some reason, it takes 5x longer than `0.13.1` to load devices and online devices and the namespace.

Then, I saw this
<img width="952" alt="Screenshot 2024-01-24 at 08 49 49" src="https://github.com/shellhub-io/shellhub/assets/4641317/47516323-a88a-4b22-aee5-951812ef7b74">

Which I thought was weird because I didn't shut down this EC2 instance. I checked on EC2 and sure enough it was still up and running, and I could ssh into it manually. So I did.

I checked the docker logs for the agent and everything was fine, pings every 10 minutes of the instance but the version of the agent was still `0.13.1`.

So I stopped the agent on my child machine, rm-ed it and ran the register device curl once more so this machine would have the `0.14.1` agent installed.

I then checked the Shellhub dashboard again, still offline. Current logs of the agent:

```
time="2024-01-24T07:46:35Z" level=info msg="Setting log level" log_level=info
time="2024-01-24T07:46:35Z" level=info msg="Starting ShellHub" mode=multi-user version=v0.14.1
time="2024-01-24T07:46:35Z" level=info msg="Listening for connections" mode=multi-user preferred_hostname= server_address="https://shellhub.xxx.com:443" tenant_id=xxx version=v0.14.1
time="2024-01-24T07:46:35Z" level=info msg="Sleeping for 24 hours" mode=multi-user preferred_hostname= server_address="https://shellhub.xxx.com:443" tenant_id=xxx version=v0.14.1
time="2024-01-24T07:46:38Z" level=info msg="Server connection established" hostname=xxx namespace=pre-production server_address="https://shellhub.xxx.com:443" ssh_server="shellhub.xxx.com:2299" sshid=pre-production.xxx@shellhub.xxx.com
```

(Please note I've replaced manually sensitive info by `xxx`)

### Edition

Community

### Version

0.14.1

**Comment by heiytor** [comment]
Hi, @Seluj78

We're actively working on reproducing the error, and I'll keep you updated on our progress. In the meantime, could you please provide details about your device?

Concerning the version of the devices, those running the Docker agent can check the Shellhub instance version and perform self-updates. This process occurs once a day.

**Comment by Seluj78** [comment]
> We're actively working on reproducing the error, and I'll keep you updated on our progress. In the meantime, could you please provide details about your device?

Sure thing ! The shellhub instance is hosted on AWS on a t2.medium and the `child` instance is a `t2.micro`. They both are running `ubuntu 22.04` from AWS. When setting both of them up, I ran `sudo apt update && sudo apt upgrade` before installing docker and oh-my-zsh (and zsh).

For the shellhub instance, Here is my `.env.override`

```
SHELLHUB_SSH_PORT=2299
SHELLHUB_AUTO_SSL=true
SHELLHUB_DOMAIN=shellhub.xxx.com
SHELLHUB_REDIRECT_TO_HTTPS=true
```
 
> Concerning the version of the devices, those running the Docker agent can check the Shellhub instance version and perform self-updates. This process occurs once a day.

Alright, well I had it update manually by running

```
docker stop CONTAINER_ID
docker rm shellhub
curl -sSf "https://shellhub.xxx.com/install.sh?tenant_id=xxx" | sh
```

Do tell me if you need more information

**Comment by heiytor** [comment]
Is the device still offline? If so, could you please try connecting to see if it works?

**Comment by Seluj78** [comment]
The device is still offline on the shellhub interface but it's online on EC2. I can connect to it using normal SSH but not through shellhub because it's marked as offline

**Comment by heiytor** [comment]
Please check if you can connect to the device via Shellhub even if it is offline. Since your `SHELLHUB_SSH_PORT` is 2299, the command `ssh -p 2299 <user>@<hostname>@<domain>` should work.

**Comment by Seluj78** [comment]
Nope, can confirm this fails with a timeout

**Comment by otavio** [comment]
Reverting back to older release is a stopgap solution. Please see if you find more information so we can fix it in future.

**Comment by Seluj78** [comment]
Ok, well this morning I've `make stop` then `make start` and it worked

Everything is back to normal, the device is online and the API is fast.

What the hell happened ? I have no clue, but now I can get back to implementing it. Thank you very much !
