### ISSUE TITLE
Unable to ssh into device or connect using the browser

### ISSUE THREAD

**Issue by rohitmediratta** [shellhub-io/shellhub#3479]
### Description

I have an Ubuntu 22.04 machine that is Registered and Online (as per Dashboard on shellhub).
When I try to connect from the browser or via ssh USER @ SSHID, I get the following error

user:~/workspace/$ ssh <USER>@SSHID
USER @ SSHID's password:
/bin/sh: 0: Illegal option --
Connection to cloud.shellhub.io closed.

What could be debugged further?
On the device the following was executed successfully
curl -sSf "https://cloud.shellhub.io/install.sh?tenant_id=HIDDEN" | sh

### Edition

Community

### Version

v0.14.1

**Comment by gustavosbarreto** [comment]
@rohitmediratta Could you please provide the output of the following command on your Ubuntu 22.04 machine?

```
ls -l /bin/sh
```

**Comment by henrybarreto** [comment]
Sorry. I have linked the wrong issue on my PR.

**Comment by rohitmediratta** [comment]
no worries, let me know if you need anything from my setup for this.

**Comment by henrybarreto** [comment]
@rohitmediratta, cloud you run this command?

```
ls -l /bin/sh
```

**Comment by rohitmediratta** [comment]
~ > ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Dec 22 11:52 /bin/sh -> dash*
~ >
This was run when my machine was registered, but not "online". I dont think it should matter, but providing this info just fyi..

**Comment by henrybarreto** [comment]
Hi, @rohitmediratta

Thank you for your patience.

I have been trying to reproduce your issue, but the connection worked file.
