### ISSUE TITLE
Incorrect default per_page on GET /api/devices

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3490]
### Description

Like the title says. The default value for `per_page` for the API route `/api/devices` is, according to your documentation, `10`.

Currently, as of `0.14.1`, it's `1`

Please update the documentation or the code to reflect the change

### Edition

Community

### Version

0.14.1

**Comment by Seluj78** [comment]
Thank you very much, and no worries, thanks for the reactivity.

**Comment by Seluj78** [comment]
Can confirm this has been fixed as of `0.14.3-rc1`

**Comment by bonnlee2024** [comment]
This bug also exist in v0.16.0.   

request url: http://{restApiUrl}/api/devices?page=1&per_page=2
it dosn't work. and return all devices.
