### ISSUE TITLE
What is the public URL ?

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3493]
### Description

In your documentation, more specifically your community OpenAPI specification, a `public_url` mentionned multiple times. I couldn't find it anywhere. What is it ? Could I have more information ?

<img width="510" alt="Screenshot 2024-01-29 at 14 40 25" src="https://github.com/shellhub-io/shellhub/assets/4641317/ff787516-5c9f-44dc-88d6-6b9445f01dcf">

### Edition

Community

### Version

0.14.1

**Comment by henrybarreto** [comment]
Device's public URL is a feature what allows a device to expose an HTTP service running inside it.  Currently, It is in an alpha state, so we have disabled by default.

**Comment by henrybarreto** [comment]
We think that, as the feature is incomplete, and probably will be reworked, documenting it at this stage could be misleading.

We will add this information to the OpenAPI as soon as possible.
