### ISSUE TITLE
/api/devices doesn't return a list with the same order

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3494]
### Description

Using the endpoint `GET /api/devices`, I expect to get a list of devices that are always the same order.

With 3 devices, running my script that calls `/api/devices?per_page=100`returns the list sorted seemingly randomly. It might be the same for a few runs then change again.

### Edition

Community

### Version

0.14.1

**Comment by heiytor** [comment]
Hi, @Seluj78

You can use ***sort_by*** and ***order_by*** to enforce a sort order. For example, with `/api/devices?per_page=100&order_by=desc&sort_by=last_seen`, it will return the list of devices with the most recently seen devices first.

In any case, I'm trying to reproduce this. Could you please tell me how many devices you have? And, if you know, how many requests you need to make to get a randomly sorted list?

**Comment by Seluj78** [comment]
[![asciicast](https://asciinema.org/a/tSCUZNhhrRxekWg27m5jMYSJW.svg)](https://asciinema.org/a/tSCUZNhhrRxekWg27m5jMYSJW)

As you can see it seems like the sort/order is by last seen maybe ? It would make more sense if the default sort order was by name IMO

**Comment by heiytor** [comment]
Taking a look at the function that retrieves the list of devices, when none of the sorting or ordering options are provided, the query will not include this expression. I'm not a MongoDB specialist, but I believe that's the reason the output may be non-deterministic, leading to a randomly ordered list. You can view the code [here](https://github.com/shellhub-io/shellhub/blob/master/api/store/mongo/device.go#L24).

Sorting by name is already possible, and this is the original [example](https://docs.shellhub.io/developers/openapi/community#tag/devices/operation/getDevices) of the documentation. So, `/api/devices?per_page=100&order_by=desc&sort_by=name` should work in your case.

We will consider employing this default approach and will keep you informed of any updates on this matter.

**Comment by Seluj78** [comment]
Alright thanks. I was just wondering if this was a bug.

In my opinion, it should be sorted by name by default so that the list of devices, when retrieved programmatically doesn't change from call to call (unless renamed) or maybe sorted by ID. In any case, I'll let you close the issue if you don't think it's necessary

**Comment by gustavosbarreto** [comment]
We plan to modify the default device list order for API v2. However, to ensure compatibility for existing users, we are maintaining the current behavior.

**Comment by Seluj78** [comment]
> We plan to modify the default device list order for API v2. However, to ensure compatibility for existing users, we are maintaining the current behavior.

Great ! Thank you
