### ISSUE TITLE
Shellhub Python SDK

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3497]
### Description

Hi,

I'm working on a python SDK to integrate with my code and I will publish it on pypi.org and I was wondering if you had something similar planned or if it was ok for me to take the name `shellhub` as a package name ?

The package will be open source of course, hosted for now in https://github.com/Seluj78/shellhub-python so it's usable and editable by everyone

I still need to push my code, documentation and tests

### Edition

Community

### Version

0.14.1

**Comment by otavio** [comment]
Did you see that our OpenAPI can generate the base API client? Considering that it is intended for API use, wouldn't 'shellhub-api' or similar be more appropriate?

**Comment by Seluj78** [comment]
I don't see what you mean with your OpenAPI base API client

Other than that, it's a standard in python to usually name the SDK around the name of the product. For example
https://pypi.org/project/discord.py/
https://pypi.org/project/PyGithub/
and many more (google, sentry, etc)

These have `py` in the name so I can maybe do something like `shellhubpy` or `shellhub-python` for the pip install but inside the code, the import will be

```python
from shellhub import ...
```

**Comment by heiytor** [comment]
OpenAPI can be used to generate SDKs for different languages. Inside your *devscripts*, you can find a useful [example](https://github.com/shellhub-io/shellhub/blob/master/devscripts/openapi) that generates a client for TypeScript.

For Python development, I'm almost certain that you can use [this](https://github.com/openapi-generators/openapi-python-client) package. The [official](https://github.com/OpenAPITools/openapi-generator) cli is also an option.

**Comment by Seluj78** [comment]
Oh I never knew that. I could definitely try that but I cannot find your OpenAPI file :/

And in any case, I personally prefer to have my own implementation :)

**Comment by otavio** [comment]
I have no objections about the package name. Let's wait and see what @gustavosbarreto thinks.

Regarding the OpenAPI, you can download it from [here] (https://docs.shellhub.io/developers/openapi/). I suggest you give it a try as it can significantly reduce the amount of work and hassle required to keep the client up to date. We use the OpenAPI to generate the UI API client and it works very well.

**Comment by Seluj78** [comment]
Thank you, I've finally found the download button 😅 

I'll let you know what I decide to do.

**Comment by gustavosbarreto** [comment]
> @otavio: I have no objections about the package name. Let's wait and see what @gustavosbarreto thinks.

I also have no objections regarding the package name

**Comment by Seluj78** [comment]
I've thought about it and I still think I'll prefer coding the SDK myself. I've looked through how the OpenAPI code works and I personally don't like it, and I find there is too much bloat

In any case, I opened my first PR on my SDK, if you want to take a look around, I'd love some reviews

https://github.com/Seluj78/shellhub-python/pull/1

I'm closing this issue for now

**Comment by Seluj78** [comment]
Just as a heads up, I found GitHub's openapi specification : https://github.com/github/rest-api-description

But people still use https://github.com/PyGithub/PyGithub and not a generated code from an openApi generator, which is mainly why I chose to do the same :)
