### ISSUE TITLE
How's performance with hundreds/thousands of machines and multiple SSH connections ?

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3503]
### Description

I just thought about this while writing this https://github.com/shellhub-io/shellhub/discussions/3476#discussioncomment-8326475

What's the perfomance impact of having 2500+ devices registered on shellhub ?

What's the performance impact of having, let's say 100 SSH connections at the same time ? (I don't know how many we have and have no way of knowing)

Currently my preprod shellhub instance is a t2.micro on AWS for tests but I am wondering what size I should plan for for the production instance with the 2500 machines and many simultaneous ssh connections

### Edition

Community

### Version

N/A

**Comment by otavio** [comment]
It's important to note that the community version of ShellHub is generally intended for hobbyist or non-critical environments. While it provides a great solution for managing devices and SSH connections, it may not be optimized for the demands of a professional and critical production environment.

Regarding your concern about instance size, you're correct in pointing out that it's not the sole factor impacting performance. Server configuration, network conditions, and other variables also play crucial roles. Upgrading the instance size may help, but it's equally important to consider optimizing server configurations, implementing efficient network management, and monitoring resource usage.

For users seeking a solution tailored for professional and critical environments, we offer the ShellHub Managed Enterprise option. This version is designed to meet the demands of larger deployments and critical use cases. If you're interested, we can set up an evaluation server for you to test its performance and suitability for your specific requirements.

Feel free to let us know if you have any further questions or if you'd like to explore the ShellHub Managed Enterprise option for your production needs.

**Comment by Seluj78** [comment]
Yes of course it makes total sense. I had seen that you had an enterprise version of ShellHub, and I will see with my superiors if it's something we would like to use, but I cannot take that decision.

In any case I will let you know what is decided, and if we do not go for the enterprise version, I will be sure to report on the performances of the community version so you can know how it scales and what might be bottlenecks
