### ISSUE TITLE
500 on base64 query

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3522]
### Description

I was trying to make a filtered query and got a 500 when doing this query

`GET https://shellhub.example.com/api/devices?page=1&per_page=100&filter=W3sidHlwZSI6InByb3BlcnR5IiwicGFyYW1zIjp7Im5hbWUiOiJuYW1lIiwib3BlcmF0b3IiOiJjb250YWlucyIsInZhbHVlIjoidCJ9fV0`

No clue why, as I just copied the base64 from the UI when searching for the letter `t` in the search bar

### Edition

Community

### Version

0.14.1

**Comment by henrybarreto** [comment]
Hi, @Seluj78. 

This problem seems to be caused by a base64 decode error.  Investigating it, I have noticed that the resultant request from typing `t` on our UI search bar is missing a `=` on its end.

Something like this, should work.
```bash
 http -v -A bearer -a "$token" GET http://localhost/api/devices\?page\=1\&per_page\=100\&filter\=W3sidHlwZSI6InByb3BlcnR5IiwicGFyYW1zIjp7Im5hbWUiOiJuYW1lIiwib3BlcmF0b3IiOiJjb250YWlucyIsInZhbHVlIjoidCJ9fV0\=
```

**Comment by Seluj78** [comment]
Right, I just tested again and indeed it seems like I forgot to copy a `=`... My bad!

On the other end though, I think a more explicit message and something other than a 500 would benefit greatly the API users :)

**Comment by henrybarreto** [comment]
I strongly agree. We are planning to work on the messages as soon as possible.

**Comment by Seluj78** [comment]
Great, do you want me to open another issue/feature request about this message for you to track it ?
