### ISSUE TITLE
acceptable doesn't represent if a device is acceptable

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3526]
### Description

While testing my code, I realized that the `acceptable` field in a device doesn't represent if a device can be accepted

![Screenshot 2024-02-08 at 19 05 02](https://github.com/shellhub-io/shellhub/assets/4641317/844f6087-302f-4b99-9d31-16b1091c0c21)
![Screenshot 2024-02-08 at 19 05 25](https://github.com/shellhub-io/shellhub/assets/4641317/1ff5b13a-7608-46fe-81a0-b59185423a6b)

### Edition

Community

### Version

0.14.1

**Comment by Seluj78** [comment]
It does seem that `status` == `pending` so I can use that while this is being fixed

**Comment by Seluj78** [comment]
Oh okay this makes sense, I don't think this is documented, hence the confusion. I will use the `status` field from now on

**Comment by henrybarreto** [comment]
No problem. You are right; we will document it as soon as possible.

**Comment by Seluj78** [comment]
Do you want to keep this issue open for tracking for the documentation ? Or maybe another issue ?
