### ISSUE TITLE
Missing documentation on `acceptable` field

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3527]
### Description

When calling the API about a device, there's a field called `acceptable`

To me, it sound like a `bool` that represents if a device can be accepted.

It turns out it isn't (see #3526) and the documentation needs to be updated

### Edition

Community

### Version

0.14.1

**Comment by henrybarreto** [comment]
> To me, it sound like a `bool` that represents if a device can be accepted.

In fact, `acceptable` is exactly this. When a device cannot be accepted for any reason, its status changes to `false`. Otherwise, unless it is already accepted, its state is `true` for `acceptable`. 

Isn't the current behavior?

**Comment by Seluj78** [comment]
When I see this variable, I expect it to be `True` when a device is pending and `False` when a device is already accepted.

@henrybarreto you explained in #3526 that `acceptable` is only used in your cloud service for device limits, hence the confusion :)

I suppose a big explanation in the docs would be welcome for this field as, at first glance, it really isn't clear what it represents

**Comment by henrybarreto** [comment]
> When I see this variable, I expect it to be `True` when a device is pending and `False` when a device is already accepted (Nothing to do with device limits etc).

You are correct. This should be the right behavior. What I have explained was the “why” of it. It was a misunderstanding from my side.

Are the field working as expected?

**Comment by Seluj78** [comment]
>You are correct. This should be the right behavior. What I have explained was the “why” of it. It was a misunderstanding from my side.

No worries!

>Are the field working as expected?

Sadly no. The `status` field is correct and it is what I am using for my `accept()` method on my sdk (see https://github.com/Seluj78/shellhub-python/blob/e9080a3010808ac87a04eef3a5ef5a62b70f0af0/shellhub/models/device.py#L135)
But when I tried to accept a pending device only based on the `acceptable` field, it was set as False but the device was `pending` (see https://github.com/Seluj78/shellhub-python/commit/a6631514c52329157eb98eb1d00bffb6b3bb06f7#diff-0df71759cb5f7aa308a761c2561b6edbe3fea6b3211cb747a1e0bc94a165aa0bL109-L110).

**Comment by Seluj78** [comment]
Amazing, thank you very much! 

Do let me know if there is anything I can do to help

**Comment by Seluj78** [comment]
I see you closed this as completed. Can I have an overview of what's changed ? Has the documentation updated ? :)
