### ISSUE TITLE
Webshell hangs when instance is rebooted

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3541]
### Description

Steps to reproduce:

Have an instance on shellhub and connect to it via webshell
reboot the instance via another shell or a UI

Expected result:

A message that explains the connection was lost

### Edition

Community

### Version

0.14.1

**Comment by heiytor** [comment]
Hi, @Seluj78,

This issue is a duplicate of #3504, so I'll close this one. We will keep you updated as this feature is developed.
