### ISSUE TITLE
missing link -> 404 on https://github.com/shellhub-io/shellhub/blob/master/cli/README.md

### ISSUE THREAD

**Issue by pflegende** [shellhub-io/shellhub#3543]
### Description

on https://github.com/shellhub-io/shellhub/blob/master/cli/README.md
you link to a help-section by:
https://docs.shellhub.io/admin-manual/managing/
but this link reply with 404

😀 
#service-Issue
![image](https://github.com/shellhub-io/shellhub/assets/52720420/2fe292e9-f696-45c0-b2ba-65d5dfe2a2f0)

not at all

### Edition

Community

### Version

cloud

**Comment by heiytor** [comment]
Hi, @pflegende,

I've linked a PR to fix this. While waiting for it to be merged, you can access the correct URI [here](https://docs.shellhub.io/self-hosted/administration).
