### ISSUE TITLE
Ansible does not work through shellhub

### ISSUE THREAD

**Issue by limeborn** [shellhub-io/shellhub#3545]
### Description

When trying to use ansible with shellhub,  we get the following 

```
# ansible all -m ping

root@NAME@shellhubhost | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1707919329.8230567-109374-186821264037102 `\" && echo ansible-tmp-1707919329.8230567-109374-186821264037102=\"` echo ~/.ansible/tmp/ansible-tmp-1707919329.8230567-109374-186821264037102 `\" ), exited with result 2, stdout output: /bin/bash: -c: line 1: syntax error near unexpected token `('\n/bin/bash: -c: line 1: `/bin/sh -c ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1707919329.8230567-109374-186821264037102 `\" && echo ansible-tmp-1707919329.8230567-109374-186821264037102=\"` echo ~/.ansible/tmp/ansible-tmp-1707919329.8230567-109374-186821264037102 `\" ) && sleep 0'\n",
    "unreachable": true
}

```

When executing with a direct ssh connection it works like expected. 

The corresponding ansible hostfile looks like this:
```
[namespace]
root@NAME@shellhubhost
```

### Edition

Community

### Version

v0.14.3

**Comment by gustavosbarreto** [comment]
Hi @limeborn,

The PR #3561 has been submitted to address the issue that was preventing the execution of Ansible commands on ShellHub.

Additionally, to configure the Ansible inventory in a way that is compatible with ShellHub, the inventory entry for your target host needs to include the complete SSHID value, including the username. This ensures compatibility with ShellHub's SSH access mechanism.

The format should be:

```
user@namespace.device@server
```

When running Ansible commands, ensure that you do not specify a username using the `-u` option. This allows Ansible to use the username specified in the inventory file for connecting to the target host.
