### ISSUE TITLE
The gateway container keeps timing out waiting for the ACME server on first start

### ISSUE THREAD

**Issue by merlinran** [shellhub-io/shellhub#3639]
### Description

It's when `SHELLHUB_AUTO_SSL` is set. In my case, this line
https://github.com/shellhub-io/shellhub/blob/12e51169339893368c58fd156210d5951f55a5ea/gateway/entrypoint.sh#L71
 starts the server on `0.0.0.0`, while `wait_for_acme_webserver` https://github.com/shellhub-io/shellhub/blob/12e51169339893368c58fd156210d5951f55a5ea/gateway/entrypoint.sh#L33  in my case, gets `localhost` resolved to `::1` and never tries the IPv4 one.

I guess the simplest fix here could be replacing `nc` with `curl -sSf http://localhost > /dev/null`, which tries all resolved IPs.

### Edition

Community

### Version

v0.14.2

**Comment by merlinran** [comment]
Alternatively maybe replace NGINX with Caddy or something with ACME support, to simplify things. https://www.eff.org/deeplinks/2024/03/should-caddy-and-traefik-replace-certbot

**Comment by gustavosbarreto** [comment]
> ### Description
> It's when `SHELLHUB_AUTO_SSL` is set. In my case, this line
> 
> https://github.com/shellhub-io/shellhub/blob/12e51169339893368c58fd156210d5951f55a5ea/gateway/entrypoint.sh#L71
> 
> 
> starts the server on `0.0.0.0`, while `wait_for_acme_webserver`
> https://github.com/shellhub-io/shellhub/blob/12e51169339893368c58fd156210d5951f55a5ea/gateway/entrypoint.sh#L33
> 
> in my case, gets `localhost` resolved to `::1` and never tries the IPv4 one.
> I guess the simplest fix here could be replacing `nc` with `curl -sSf http://localhost > /dev/null`, which tries all resolved IPs.
> 
> ### Edition
> Community
> 
> ### Version
> v0.14.2

@merlinran Could you create a pull request with the proposed fix?  Since replacing NGINX with Caddy or any other API gateway isn't on the roadmap right now due to the significant effort involved.

**Comment by merlinran** [comment]
> ... replacing NGINX with Caddy or any other API gateway isn't on the roadmap right now due to the significant effort involved.

Is this change desirable? Is there any downsides or caveats of doing this? I can work on that if I get a :+1: Do you have any preference on Caddy vs Traefik vs (any other options)?

**Comment by gustavosbarreto** [comment]
> > ... replacing NGINX with Caddy or any other API gateway isn't on the roadmap right now due to the significant effort involved.
> 
> Is this change desirable? Is there any downsides or caveats of doing this? I can work on that if I get a 👍 Do you have any preference on Caddy vs Traefik vs (any other options)?

Yes, this change is desirable, and we have a preference for Traefik.
