### ISSUE TITLE
bug: cannot run as non-root user

### ISSUE THREAD

**Issue by landgraf** [shellhub-io/shellhub#3736]
### Description

SHELLHUB_SINGLE_USER_PASSWORD is ignored and agent fails to start

### Steps to Reproduce

Try to run agent without root permissions

### Expected Behavior

Agent is running

### Edition

Community

### Version

606156b4d1134f74f037d2d640be3fcaeb17f4a5

### Related Logs

```shell
pavel@desktop /tmp/shellhub/agent $ export SHELLHUB_SINGLE_USER_PASSWORD="$6$7mQ0Mt.FKyAyG7vK$666F3AC8ERmzg.q8aGFVAY7s7r4xStCLGqdnF7KOLaC3arIVjfq5xznLAQ2ISDWaqpKY0moY5CX3IXp7Vx3th/"
pavel@desktop /tmp/shellhub/agent $ ./agent 
ERRO[0000] When running as non-root user you need to set password for single-user mode by SHELLHUB_SINGLE_USER_PASSWORD environment variable. 
ERRO[0000] You can use openssl passwd utility to generate password hash. The following algorithms are supported: bsd1, apr1, sha256, sha512. 
ERRO[0000] Example: SHELLHUB_SINGLE_USER_PASSWORD=$(openssl passwd -6) 
ERRO[0000] See man openssl-passwd for more information. 
pavel@desktop /tmp/shellhub/agent $ env | grep SHELLHUB
PRIVATE_KEY=__SHELLHUB_PRIVATE_KEY__
SHELLHUB_SINGLE_USER_PASSWORD=mQ0Mt.FKyAyG7vK66F3AC8ERmzg.q8aGFVAY7s7r4xStCLGqdnF7KOLaC3arIVjfq5xznLAQ2ISDWaqpKY0moY5CX3IXp7Vx3th/

```
```


### Related Code

_No response_

### Additional Information

_No response_

**Comment by henrybarreto** [comment]
Hi, @landgraf, thanks for your reporting. 

I am investigating it right now

**Comment by henrybarreto** [comment]
So, we located the issue.

The problem is with the environmental variable name, what isn't matching with the documentation showed; sorry.

Use, please, ` SHELLHUB_SIMPLE_USER_PASSWORD` instead of  `SHELLHUB_SINGLE_USER_PASSWORD`, it will probably work well.

We will work on an adaptation to make the right variable work with backward compatibility with the wrong one.

**Comment by landgraf** [comment]
I can confirm this works. Thank you!

**Comment by henrybarreto** [comment]
> I can confirm this works. Thank you!

I’m glad I could help.
