### ISSUE TITLE
How to build shellhub-agent from source?

### ISSUE THREAD

**Issue by openedhardware** [shellhub-io/shellhub#402]
![image](https://user-images.githubusercontent.com/16890683/93201573-f4ea6580-f783-11ea-9638-eb97ff484ea5.png)

I am actually going to use this awesome service on a balena device: https://www.balena.io/docs/learn/welcome/introduction/

Balena uses `balena-cli`, which is very similar to docker but slightly different.

In order to use shellhub in conjunction with balena, I have to involve this source of shellhub-agent to the `docker-compose.yml` of a balena project to build from source.

But I can't find the source of the shellhub-agent?

Cheers.

**Comment by otavio** [comment]
The source is here: https://github.com/shellhub-io/shellhub/tree/master/agent

The development `docker-compose` file has the agent running, for development. It can serve as inspiration for your setup. See: https://github.com/shellhub-io/shellhub/blob/master/docker-compose.dev.yml#L52-L87

**Comment by gustavosbarreto** [comment]
See https://docs.shellhub.io/user-manual/installing/#installing-from-source-code

**Comment by openedhardware** [comment]
Wow, thanks for your clarification!
Let me try that right now.

**Comment by gustavosbarreto** [comment]
Hey @openedhardware take a look at my recent experiment integrating ShellHub with Balena:  https://github.com/gustavosbarreto/shellhub-balena
