### ISSUE TITLE
UI Error in Safari

### ISSUE THREAD

**Issue by MPP-SG** [shellhub-io/shellhub#408]
### General information
version of ShellHub): 0.4.0 (ShellHub is running on localhost in a docker-compose container
Safari: 13.1.2 (14609.3.5.1.5)
Chrome: Version 84.0.4147.135
Mac OSX: 10.14.6 (macOS Mojave)

### Problem description
Some icons are not shown correctly in the UI and the navigations fails. The problem occurs only in Safari.

### Problem story
- After logging into ShellHub some UI icons are not shown.
  - Attached are two screenshots to illustrate the icon problem
- Also the navigation in the left menu bar is not working in the Safari browser. The following menu entries produce some errors. The UI didn't respond to the click event and didn't transition to the new view. For the error log please refer to the attachments section.
  - Devices
  - Sessions
  - Firewall Rules

#### Screenshot in the Chrome browser
<img width="1432" alt="ShellHub_Chrome" src="https://user-images.githubusercontent.com/48908846/93320637-99ff4f80-f811-11ea-9aa3-d638a674b9f6.png">

#### Screenshot in the Safari browser
<img width="1359" alt="ShellHub_Safari" src="https://user-images.githubusercontent.com/48908846/93320647-9cfa4000-f811-11ea-80fa-b6ed2216bf43.png">

#### Error Log Devices
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (devices.41bbfcbc.js:1)
[Error] ChunkLoadError: Loading chunk devices failed.
(missing: http://localhost/js/devices.41bbfcbc.js)
	o (chunk-vendors.c38e9b1e.js:39:20557)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:21028)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:16875)
	promiseReactionJob
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-a6ebbc5e.9004940f.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-ebd2cd9e.d7631a6b.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-25e298bc.960fc29b.js:1)

#### Error Log Sessions
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-a6ebbc5e.9004940f.js:1)
[Error] ChunkLoadError: Loading chunk chunk-a6ebbc5e failed.
(missing: http://localhost/js/chunk-a6ebbc5e.9004940f.js)
	o (chunk-vendors.c38e9b1e.js:39:20557)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:21028)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:16875)
	promiseReactionJob
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-5d149bb1.b50e4281.js:1)

#### Error Log Firewall Rules
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-a6ebbc5e.9004940f.js:1)
[Error] ChunkLoadError: Loading chunk chunk-a6ebbc5e failed.
(missing: http://localhost/js/chunk-a6ebbc5e.9004940f.js)
	o (chunk-vendors.c38e9b1e.js:39:20557)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:21028)
	(anonyme Funktion) (chunk-vendors.c38e9b1e.js:39:16875)
	promiseReactionJob
[Error] SyntaxError: Unexpected token '<'
	(anonyme Funktion) (chunk-2ce4287c.45868ea5.js:1)

**Comment by gustavosbarreto** [comment]
@leonardojoao do you have any idea on how it is possible to test it using Safari browser without a Mac?

I think that Mac users should not be ignored

**Comment by leonardojoao** [comment]
So, I tested the project using the scope configuration specification.

Fisrt, I runned the ShellHub version 0.4.0. Then, I created the tunnel to shared my localhost environment. 
Finally, I used the URL generated for use in an online application, you have the possibility to select the operating system, browser and version list.

But, I can't reproduce the error.

**Comment by otavio** [comment]
@MPP-SG, we are unable to reproduce this issue. As we did not receive feedback since September, we are assuming it has been fixed.

Please reopen otherwise.
