### ISSUE TITLE
bug: Error occurred while updating device status by restapi

### ISSUE THREAD

**Issue by bonnlee2024** [shellhub-io/shellhub#4096]
### Description

Error occurred while updating device status by restapi

1.request the api "Update device status",  Return error message “400 bad request”
my url format: http://{serverAddress}/api/devices/{uid}/{status}    --The status value is  "accept" "reject" "pending"  or "unused"

2.request the api "Update device status to offline", Return error message "405 not allowed"
my url format: http://{serveraddress}/internal/devices/{uid}/offline

And I'm sure the api token was correct.

### Steps to Reproduce

1.Install the agent and accept
2.request the restapi

### Expected Behavior

i want the restapi works normally

### Edition

Community

### Version

v0.16.0

**Comment by henrybarreto** [comment]
Hi, @bonnlee2024 

Thank you for helping to improve ShellHub!

First, the `internal` paths are intended for use between the services only, so they aren't reachable outsize the container's network, what returns the error informed.

About the first request, that one to update the device status, would you mind providing additional information like the HTTP method used and the tool you are using to make the HTTP requests?

**Comment by bonnlee2024** [comment]
> Hi, @bonnlee2024
> 
> Thank you for helping to improve ShellHub!
> 
> First, the `internal` paths are intended for use between the services only, so they aren't reachable outsize the container's network, what returns the error informed.
> 
> About the first request, that one to update the device status, would you mind providing additional information like the HTTP method used and the tool you are using to make the HTTP requests?

My testing tool is postman,  used HTTP request,    request method was Patch,   request url like this "http://10.0.10.150/api/devices/1234a453c8c6746bd0db7a733f8c68895936cf4078e8c4e5566b7062c98cb7c7/pending"

it dosen't work

**Comment by henrybarreto** [comment]
@bonnlee2024, once your device is accepted, it may only be deleted. Only pending devices can have their status changed to `rejected`.
