### ISSUE TITLE
REST API for device management and other features?

### ISSUE THREAD

**Issue by openedhardware** [shellhub-io/shellhub#410]
Is there any REST API that I can:
- retrieve pending/accepted/rejected device list including device SSHID
- accept/reject a device
- manage user
- get tenant_id
- ... ... ...

Thanks!

**Comment by gustavosbarreto** [comment]
@openedhardware Yes, there's a REST API. It's just that it is not documented yet and not is intended for public usage but we can reconsider that.

**Comment by openedhardware** [comment]
Any update here?
It's a bit annoying for us to accept each device one by one on our portal...
Is there any way to accept all devices by an API?

**Comment by gustavosbarreto** [comment]
> Any update here?
> It's a bit annoying for us to accept each device one by one on our portal...
> Is there any way to accept all devices by an API?

I did a initial work for this in: https://docs.shellhub.io/api/

**Comment by openedhardware** [comment]
Perfect! Will keep an eye on it!

Cheers.

**Comment by otavio** [comment]
@openedhardware for your needs, the current documented API is good enough? If so, we'd like to close this issue.
