### ISSUE TITLE
bug: Device is added successfully but is marked as offline

### ISSUE THREAD

**Issue by heavymp** [shellhub-io/shellhub#4193]
### Description

I instaled everything per your instruction, mostly with defaukt settings except few port changes. When I add new device using the command generated by ShellHub web gui, it is detected and added without issue but it never appears as online. The agent log indicates that it is connected to ShellHub.  

### Steps to Reproduce

Install both the shellhub server and dependencis as well as agent on same device using docker. Add device tointerface following the prompts.

### Expected Behavior

Device added but marked as offline

### Edition

Community

### Version

0.16.0

### Additional Information

![image](https://github.com/user-attachments/assets/1dccca36-f6d4-42d7-8f53-571636a39527)
![image](https://github.com/user-attachments/assets/6e3d027f-db8e-416c-9825-4c9e5228a512)
![image](https://github.com/user-attachments/assets/0bc33bac-f1a7-47ea-a2f1-ea2e97bf93b5)

**Comment by gustavosbarreto** [comment]
Please try updating to the latest stable version 0.16.4 of ShellHub and see if the issue persists.

**Comment by heavymp** [comment]
Updating and restarting the stack multiple times has resolved the problem. I can successfully connect to terminal now. Thanks.
