### ISSUE TITLE
bug: devices no longer accessible via Shellhub Cloud

### ISSUE THREAD

**Issue by CloudCray** [shellhub-io/shellhub#4292]
### Description

Attempting to connect to devices on Shellhub Cloud results in an error message.

The device is showing as "Connected" in the Web UI, and the "Last Seen" property is updated correctly in the Details page when the device is powered on.

However, attempting to connect results in a long-hanging request which ultimately returns an error message.

### Steps to Reproduce

Attempting to connect via SSH:

```
ssh <user>@<namespace>.<devicename>@cloud.shellhub.io
you cannot access the device due a policy ruleConnection closed by <X.X.X.X> port 22
```

Attempting to connect via the web portal:

```
you cannot access the device due a policy rule
Connection ended
```

### Expected Behavior

Connect to a shell session of the device.

### Edition

Cloud

### Version

0.17.0

### Additional Information

Attempted to connect to multiple devices without success.
Power-cycled one local device. "Last Seen" was updated successfully in WebUI, but still can't connect.
Was able to ssh via local network IP address, so it's not a credentials issue.

**Comment by Drakonis** [comment]
devices should be accessible now

**Comment by gustavosbarreto** [comment]
@CloudCray,

We have identified the root cause of the issue.
This has now been resolved, and connections should work as expected.

Please let us know if you encounter any further issues.

**Comment by CloudCray** [comment]
Everything is connecting again on our end - didn't even need to reboot the devices

Thank you!
