### ISSUE TITLE
[feature] Password Recovery/Reset

### ISSUE THREAD

**Issue by ItaloYeltsin** [shellhub-io/shellhub#460]
I think this is a basic feature shellhub should have before releasing an oficial version. 

To achieve such an implementation, I think we must have:

- [ ] an email template for password reset;
- [ ] an email user at shellhub.io domain (no-reply@shellhub.io);
- [ ] a password reset request page;
- [ ] a password reset page;
- [ ] captcha;
- [ ] a "forgot password link" at login page.

**Comment by otavio** [comment]
@ItaloYeltsin hello, good to see you here!

We were discussing it here but in fact, this is covered by the open-source version as it has support to manage this using the command line at [./bin/reset-user-password](https://github.com/shellhub-io/shellhub/blob/master/bin/reset-user-password).

It'd be very difficult to choose one backend to send emails to the users and would increase the complexity to start the server.

**Comment by ItaloYeltsin** [comment]
Ok, now it’s clear. Indeed, makes totally sense to the local running version, which is the open source one, to reset the password by running the local command. I thought the cloud version was open as well.
