### ISSUE TITLE
(QUESTION) What protocol does the device agent use to communicate with the gateway?

### ISSUE THREAD

**Issue by markovchainz** [shellhub-io/shellhub#486]
I checked the documentation and haven't seen any issues on this matter (apologies if I've missed something).

Many company networks have heavy restrictions on outgoing ports and protocols (i.e. I commonly see UDP communication blocked across the board). What ports/protocol does the agent use?

**Comment by gustavosbarreto** [comment]
> I checked the documentation and haven't seen any issues on this matter (apologies if I've missed something).
> 
> Many company networks have heavy restrictions on outgoing ports and protocols (i.e. I commonly see UDP communication blocked across the board). What ports/protocol does the agent use?

All communication is done via HTTP/WebSocket between agent and gateway
