### ISSUE TITLE
[Question]/[Feature ] Supporting multiple users and groups by tenants 

### ISSUE THREAD

**Issue by RotemEmergi** [shellhub-io/shellhub#490]
Hi!

I add try to add a new user to existing shellhub setup and I'm getting an error on add a new user .

There is a way to manage groups and users by tenants ?

Best Regards

**Comment by gustavosbarreto** [comment]
> I add try to add a new user to existing shellhub setup and I'm getting an error on add a new user .
 
Are you using the provided utility (`./bin/add-user`) to add a new user?

> There is a way to manage groups and users by tenants?

The only way to manage users is by using the following utilities:
* `./bin/add-user`
* `./bin/del-user`
* `./bin/reset-user-password`

**Comment by RotemEmergi** [comment]
Hi !

Yes !

use the ./bin/add-user rror on add a new user . 
using the TENANT_ID=xxxxxxx ./bin/add-user xxxxxx xxxxxxx test@test.com

**Comment by gustavosbarreto** [comment]
> Hi !
> 
> Yes !
> 
> use the ./bin/add-user rror on add a new user .
> using the TENANT_ID=xxxxxxx ./bin/add-user xxxxxx xxxxxxx [test@test.com](mailto:test@test.com)

You cannot add multiple users with the same tenant id.

**Comment by RotemEmergi** [comment]
@gustavosbarreto can you add it has feature  ?

**Comment by jakew009** [comment]
Is this something that's on the road map, especially for the cloud version?

Without it the cloud version is pretty much unusable in a production environment.

**Comment by gustavosbarreto** [comment]
@RotemEmergi @jakew009 We are working on it. It will be available both in the open-source version and in the Cloud.

**Comment by jakew009** [comment]
> @RotemEmergi @jakew009 We are working on it. It will be available both in the open-source version and in the Cloud.

Excellent, we currently use rttys, but we'd rather use Shellhub.

At the moment there is a distinct lack of security features though which makes us hesitant.

**Comment by gustavosbarreto** [comment]
Hello @jakew009 @RotemEmergi, the feature will be available in next release. Thanks for your patience.
