### ISSUE TITLE
[Question] Project status?

### ISSUE THREAD

**Issue by markovchainz** [shellhub-io/shellhub#497]
This is such a great project and I am wanting to start using it in a production environment to remotely manage a fleet of linux PC's.

I do see that the software is in BETA though... is that based on the reliability of the remote access or more to do with wanting to add more features and capabilities?

Thanks!

**Comment by otavio** [comment]
We're still adding features and polishing the project. The cloud version is still not including any payment or device limit, and we have underlying work for our enterprise version (which offers on promises installation).

It is excellent, and we've been using it on production with some of our embedded customers for a while.

**Comment by markovchainz** [comment]
Great to hear!

Is the plan to eventually focus only on the enterprise version or will there still be focus on the open source project?

**Comment by otavio** [comment]
We'll never stop working on the open-source project, but we'll have features we'll be releasing only on the enterprise version. So people can choose what better fits their needs.
