### ISSUE TITLE
Support ssh -D forwarding

### ISSUE THREAD

**Issue by jakew009** [shellhub-io/shellhub#513]
ssh -D forwarding is super useful for doing remote support as it can give you access to a device on the users LAN using the SOCKS proxy in the browser.

At the moment it doesn't seem to work with Shellhub, any plans to support it?

**Comment by gustavosbarreto** [comment]
> At the moment it doesn't seem to work with Shellhub, any plans to support it?

Our team will evaluate this request, but currently it is not on our roadmap.

**Comment by henrybarreto** [comment]
The next release will bring the support for Local Port Forward and Dynamic Port Forward.
