### ISSUE TITLE
Copy SSHID to clipboard will not result the right ID

### ISSUE THREAD

**Issue by andy-freund** [shellhub-io/shellhub#531]
Copy SSHID to clipboard will not result the right ID.

Examples (the value is floating):
solarmanager.70-82-0e-11-7b-d3@cloud.shellhub.io
solarmanager.b8-27-eb-d4-eb-e8@cloud.shellhub.io
...
![Bildschirmfoto 2020-11-04 um 11 57 03](https://user-images.githubusercontent.com/65135994/98103529-6c3f9a00-1e95-11eb-86fa-b996eecc2208.png)

**Comment by gustavosbarreto** [comment]
@leonardojoao can you take a look into this please?
