### ISSUE TITLE
ShellHub client does not work on Centos 7

### ISSUE THREAD

**Issue by ichintu** [shellhub-io/shellhub#545]
It seems like for the client to work the kernel needs namespace support. Just a curious question would it not be better to make the client portion a go / Python binary? rather than a docker container?

I get this error and based on my google research i concluded that this is a kernel issue as I was able to get it to work by upgrading my kernel to:

`Linux 5.9.9-1.el7.elrepo.x86_64 x86_64`

Error:
`nsenter: cannot open /proc/1/ns/cgroup: No such file or directory.`

**Comment by otavio** [comment]
@ichintu, thanks for getting in touch. Are you installing it using the Docker container or natively?

In fact, the Docker container is one of the possible ways to install the agent. You can [run it natively](https://docs.shellhub.io/reference/agent/installing/#installing-from-source-code), and we could in the future offer distribution packages (RPM, Dpkg, ...) for an easy installation.

**Comment by ichintu** [comment]
I have tried several ways to build the agent as described on that page and always run into the same issue. Please see the attached screenshot
![image](https://user-images.githubusercontent.com/7726401/99840669-fd23a000-2b3a-11eb-874e-0f6c962f1dec.png)

**Comment by otavio** [comment]
Oh, this is easy. You need to provide the version. We do it in Yocto Project as:

https://github.com/shellhub-io/meta-shellhub/blob/master/recipes-core/shellhub/shellhub-agent_0.4.0.bb#L27

**Comment by ichintu** [comment]
Doh! this was too easy. For anyone else struggling leaving this here:
`go build -ldflags "-X main.AgentVersion=0.3.7"`

Last question is there a way to pass the environment variables as a config file or hard code it in the binary?

**Comment by otavio** [comment]
What we did in Yocto Project is we use an `/etc/default/shellhub-agent` file, and use it on the service. For reference:

https://github.com/shellhub-io/meta-shellhub/blob/master/recipes-core/shellhub/shellhub-agent-config.bb#L19

and

https://github.com/shellhub-io/meta-shellhub/blob/master/recipes-core/shellhub/shellhub-agent/shellhub-agent.service#L8

**Comment by otavio** [comment]
By the way, would you be interested in providing better documentation on how to do all this?

**Comment by ichintu** [comment]
Sure i will update tomorrow. I didn't want to use Environment variables. so i hard coded the information in the binary. I modified the main.go file to set the opts.* values before compiling. I am not a coder just know how to reverse / hack :P

**Comment by gustavosbarreto** [comment]
> Doh! this was too easy. For anyone else struggling leaving this here:
> `go build -ldflags "-X main.AgentVersion=0.3.7"`

Build instructions updated.

https://docs.shellhub.io/reference/agent/installing/#installing-from-source-code

**Comment by otavio** [comment]
I am closing this issue as @gustavosbarreto added the requirement to the docs.
