### ISSUE TITLE
Using ShellHub behind a nginx ssl terminator

### ISSUE THREAD

**Issue by s00500** [shellhub-io/shellhub#595]
Hey everyone, 
Awsome project!!!!

I deployed an instance of it behind my nginx reverseproxy, in my case nginx handles letsencrypt and all other things automatically (I use vestaCP)

As my nginx config just does a proxy_pass to http all the ssh websocket tunnels and the ws connection from the main webui were not working

To fix this I added: a ws location to my config like this:

```
    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header HOST $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_set_header   X-Forwarded-Proto $scheme;

      proxy_pass http://127.0.0.1:54821;
      proxy_redirect off;
    }

   location /ws/ {
            proxy_pass http://127.0.0.1:54821;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
 }

location /ssh/ {
            proxy_pass http://127.0.0.1:54821;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
 }
```

This works perfectly fine now.

Now to my 2 questions: 
Are there more ws endpoints that I would need to take care of ? (so far everything is working)
And can/should this be added to the documentation ?

Notice that in this case SSL is only handled by nginx, I have also changed the docker-compose.yml file to only expose the http port to 127.0.0.1, to not expose it to the web

Greetings and keep up the awesome work !!!

**Comment by gustavosbarreto** [comment]
Hi @s00500 

> Are there more ws endpoints that I would need to take care of ? (so far everything is working)
No. All websocket endpoints are under `/ws` and `/ssh`

> And can/should this be added to the documentation ?
I think it could be added to "Enable SSL" section in https://docs.shellhub.io/admin-manual/production-deployment/

> Notice that in this case SSL is only handled by nginx, I have also changed the docker-compose.yml file to only expose the http port to 127.0.0.1, to not expose it to the web

You can use `docker-compose.override.yml` file to override different aspects of your deployment instead of editing `docker-compose.yml` directly in order to avoid conflict with upstream code.

**Comment by s00500** [comment]
Yes, I found the note about override in the docs and already added it for configuring volumes
I will move my port change to there as well

Sound like a good place to add the info to 🙂👍

**Comment by gustavosbarreto** [comment]
@s00500 

> Sound like a good place to add the info to

Can you help us with this?

**Comment by s00500** [comment]
sure, will check if there is a better way still than the duplicated location block...

**Comment by gustavosbarreto** [comment]
@allcontributors please add @s00500 as documentation

**Comment by s00500** [comment]
Awesome =D 🎉
