### ISSUE TITLE
Possibility of removing CGO usage from the agent

### ISSUE THREAD

**Issue by s00500** [shellhub-io/shellhub#596]
The osauth package in the agent uses CGO. This blocks cross compilation using GOOS and GOARCH and makes it much harder to do at all.

As the package does mainly parse files and perform some crypto, can it not be replaced with a pure go implementation ? Or was there a specific reason why this was implemented in CGO ?

If you consider it possible to replace it I would be willing to try and submit a PR :-)

Greetings

**Comment by otavio** [comment]
If there are no side effects, I think it is worth a try. Have you found any go package which implements it?

**Comment by s00500** [comment]
Well there are a few things like this:
https://github.com/astromechza/etcpwdparse

Or this:
https://github.com/willdonnelly/passwd/blob/master/passwd.go

But it really all does not look complicated to me, so I will probably make an attempt in the next 2 weeks :-)

**Comment by shawn111** [comment]
@s00500 thanks, it is useful if we want to do cross compile.
I did other PR, let non-root can run agent.

https://github.com/shellhub-io/shellhub/pull/617/
