### ISSUE TITLE
Creating shellhub.key for the dockerless agent

### ISSUE THREAD

**Issue by calibrae** [shellhub-io/shellhub#628]
Hi.
Not really an issue, but I could not find the info anywhere.
I'm trying to deploy agents on very small machines and VMs and I don't want all the dockerd and containerd overhead.
So I've been trying the build route, which worked quite nicely, and followed the tutorial [here](https://karmine.medium.com/shellhub-setup-b7757e9ecaf6) . 
But I don't know where or what is this /etc/shellhub.key
I guess it's related to the key generation but I'm really not sure what to use.
Thanks for you help !

**Comment by gustavosbarreto** [comment]
> But I don't know where or what is this /etc/shellhub.key

The key is generated by ShellHub agent. 

> I guess it's related to the key generation but I'm really not sure what to use.

The path of key file can be modified by changing the value of `SHELLHUB_PRIVATE_KEY` environment variable

**Comment by calibrae** [comment]
And, after fiddling with SELinux, it works. Thanks @gustavosbarreto for your help. Cheers.
Kudos to the team for the amazing little tool.
