### ISSUE TITLE
Sudo questing blocked in kickstart.sh  if command from webui is used

### ISSUE THREAD

**Issue by brammp** [shellhub-io/shellhub#638]
### Issue 
When using provided command for web ui to install agent `curl "<shellhuburl>/install.sh?tenant_id=<ID>" | sh`
the installer does not wait for answer, and automatically `returns It cannot proceed, exiting`
### Possible solution
Replace the command with `sh <(curl "<shellhuburl>/install.sh?tenant_id=<ID>") `
The folowing files/lines need to be modified:
* ui/src/components/device/DeviceAdd.vue on line 95
* ui/src/components/welcome/Welcome.vue on line 218
* ui/tests/unit/components/device/DeviceAdd.spec.js on line 62
* ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js on line 11
* ui/tests/unit/components/welcome/Welcome.spec.js 84

**Comment by gustavosbarreto** [comment]
@brammp Can you please open a PR with it?

**Comment by brammp** [comment]
Yes, just finishing it up now

**Comment by brammp** [comment]
Sorry for the multiple commits and the incorect msg the commits themself,
Kida new in this world
Hope that everything is Okay now
