### ISSUE TITLE
Support SFTP

### ISSUE THREAD

**Issue by karesz123** [shellhub-io/shellhub#656]
SFTP is very useful for file transfers

I tried to connect to a device  with FileZilla(SFTP), but I got an error:

![Screenshot from 2021-01-22 13-50-37](https://user-images.githubusercontent.com/11056548/105492918-f0493700-5cb8-11eb-9b7e-ee6e47ae563d.png)

At the moment as I see it,  files can be transferred only with `SCP` command.

Is SFTP already supported or any plans to support it ?

**Comment by gustavosbarreto** [comment]
> Is SFTP already supported or any plans to support it ?

Currently, SFTP is not supported. For the most common case, this can be worked around by using SCP instead. There are no plans, in the short term, to support SFTP but it is in the roadmap for future improvement.

**Comment by BennySBoatia** [comment]
SFTP would be a really useful feature! Looking forward to it.

**Comment by gustavosbarreto** [comment]
Link: ahuahu

**Comment by karticr** [comment]
waiting for this feature.

**Comment by gustavosbarreto** [comment]
Since OpenSSH 8.8 the scp utility uses the SFTP protocol by default. So we really need support for SCP.

**Comment by gustavosbarreto** [comment]
Closed #2094
