### ISSUE TITLE
SSH step not working for me

### ISSUE THREAD

**Issue by viniciusah** [shellhub-io/shellhub#66]
I am using shellhub 0.2.1

Installation seems OK. I can insert and view devices on the web interface but cannot ssh on the remote machine.

I try from four different scenarios:
- Debian 9, same internal network, no firewall between machines;
- Debian 6, same internal network, no firewall between machines;
- Ubuntu 14, remote network, firewall between machines;
- Minimo (distro for older computer based on Debian Jessie), remote network, firewall between machines;

All scenarios give me the message "Permission denied, please try again."

When I use the same ssh command on the local machine (the same machine that runs shellhub and the device) it works.

I already search on the website project and not found anything wrong.

Any tips?

**Comment by otavio** [comment]
> All scenarios give me the message "Permission denied, please try again."

One thing to consider is that, currently, ShellHub does not support key authentication so it must use password. From the error above ("Permission denied, please try again.") it seems it is reaching the device but not logging successfully.

Some distros set `root` to only accept key authentication. Is this your use case?

**Comment by otavio** [comment]
@viniciusah we are closing this issue due to innactivity.
