### ISSUE TITLE
No 32 bits image ?

### ISSUE THREAD

**Issue by PhilRfr** [shellhub-io/shellhub#684]
Hello,

I'm looking to set up shellhub agent on a 32 bit machine. Apparently, there is no such image with tag (i386).
When I run the install script, I have
`Unable to find image 'shellhubio/agent:v0.4.2' locally
v0.4.2: Pulling from shellhubio/agent
docker: no matching manifest for unknown in the manifest list entries.`

Is it possible to add a 32 bit version ?

Thanks !

**Comment by gustavosbarreto** [comment]
Hi, currently there is no 32-bit image yet, but they are still planned. I will probably look into them next

**Comment by PhilRfr** [comment]
Right.
Tried to build the image on a 32 bits machine, and failed due to a file not being present.
I hope you can investigate it.

**Comment by gustavosbarreto** [comment]
> Right.
> Tried to build the image on a 32 bits machine, and failed due to a file not being present.
> I hope you can investigate it.

Please paste the build output

**Comment by PhilRfr** [comment]
Well, it goes smoothly until I reach
`Step 28/29 : COPY --from=builder /agent /app/
COPY failed: stat /var/lib/docker/overlay2/6461f3cbc424eb8e4c726e09d6cf3e3a81acb6fd977615f74c2768b4b553e3e2/merged/agent: no such file or directory`
