### ISSUE TITLE
self build agent is stopping after an unsuccessful authentification

### ISSUE THREAD

**Issue by MartinKuhl** [shellhub-io/shellhub#686]
I build the agent inside a docker container like described here: https://docs.shellhub.io/reference/agent/installing/#installing-from-source-code

Docker base image: Debian GNU/Linux 9 (stretch) 
Go version: 1.14.1

After an unseccessful authentification the agent stops with the following error:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/55736453/106809682-411f3f00-666c-11eb-98c5-478ea59c6b06.png">

**Comment by gustavosbarreto** [comment]
@MartinKuhl did you set the root password inside the container?

**Comment by MartinKuhl** [comment]
no I don't

**Comment by gustavosbarreto** [comment]
I cannot reproduce this bug

**Comment by gustavosbarreto** [comment]
@MartinKuhl Can you please provide step-by-step instructions on how to reproduce the problem?

**Comment by MartinKuhl** [comment]
In the current version I'm also not able to reproduce this issue
