### ISSUE TITLE
problems with customized SHELLHUB_SSH_PORT and SHELLHUB_HTTP_PORT

### ISSUE THREAD

**Issue by MartinKuhl** [shellhub-io/shellhub#689]
If I change the SHELLHUB_HTTP_PORT and SHELLHUB_SSH_PORT to the not standard ports the Web Terminal UI stays black and a SSH Client like putty close themself direct after entering the credentials.

![image](https://user-images.githubusercontent.com/55736453/107046254-b737b900-67c6-11eb-9921-f33a6fe5cf37.png)

Same Setup but with the standard ports everything works like a charm.

**Comment by gustavosbarreto** [comment]
What is the value of environment variable `SHELLHUB_HTTP_PORT` and `SHELLHUB_SSH_PORT`?

**Comment by MartinKuhl** [comment]
SHELLHUB_HTTP_PORT=9080
SHELLHUB_SSH_PORT=9022

**Comment by gustavosbarreto** [comment]
Confirmed this is an issue:

When changing the value of SHELLHUB_HTTP_PORT to anything else than 80 the ssh service cannot connect to reverse tunnel:

```
ssh_1      | time="2021-02-08T12:53:49Z" level=error msg="Failed to dial to tunnel" err="revdial listener failed to pick up connection: dial tcp 159.203.111.161:80: connect: connection refused" session=12239f5f13a821a1daaeb8bdc977693300e0d5ae99bf70e6db1fdc82e5b30c05
```
