### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by Ossanes** [shellhub-io/shellhub#700]
When I try to connect to a device using a namespace which contains a capital letter, after a enter the password I get this message:
`Invalid session target`
Changing the namespace to anything without a capital letter, it works normally.

Example:
```
$ root@Test.00-00-00-00-00-00@cloud.shellhub.io's password:
Invalid session target
Connection to cloud.shellhub.io closed.
```

**Comment by gustavosbarreto** [comment]
Since the namespace is used to generate the hostname the case should be ignored by the SSHID resolver
