### ISSUE TITLE
Shellhub container not restarting after server restart.

### ISSUE THREAD

**Issue by suegy** [shellhub-io/shellhub#716]
When setting up shellhub on my Ubuntu Server and using Docker  I can start shellhub using ./bin/docker-compose -d but upon server restart the docker containers are not restarted automatically.
To fix this I currently use a cronjob.

**Comment by otavio** [comment]
@suegy, thanks for reporting this. I believe this has been fixed in https://github.com/shellhub-io/shellhub/commit/1ce866ad542a7ebb5466fed183db101477b6b842. 

Can you apply this in your version and confirm?

**Comment by suegy** [comment]
I applied only this fix and did not upgrade from 0.5.0 and the container is now restarting after the server is restarting.
