### ISSUE TITLE
On-demand agent connections

### ISSUE THREAD

**Issue by sammck** [shellhub-io/shellhub#717]
I'm interested in adapting shellhub to an environment with a very large number of client devices that have very intermittent connectivity, have battery life concerns, are infrequently accessed via SSH (only a very small number at one time), and for which the economics of frequently reestablishing and maintaining a persistent open socket from each agent to the shellhub server doesn't make sense.  These devices are on a network with an efficient but low-bandwidth/high latency notification/push channel (through HTTP polling, SMS notification or similar). It would be nice to have a configurable feature in shellhub whereby when an SSH client attempts to connect to an agent that does not have an active agent connection, a configured subprocess command could be invoked to initiate such an out-of-band push notification to the device, followed by waiting for a configurable timeout for the device agent to establish a connection before timing out the SSH connection attempt.

On the agent side, my custom out-of-band notification handler would receive the notification and start the shellhub device agent if it was not already started.  After a configurable period of inactivity (e.g., no active SSH connections), the shellhub agent would shut itself down. Alternatively, the shellhub server could disconnect from the device agent when its connection becomes idle, and the device agent would remain disconnected until another out-of-band notification is received.

Is there anything along these lines in your roadmap? Would you consider adding such a feature or be interested in related contributions?

**Comment by gustavosbarreto** [comment]
> I'm interested in adapting shellhub to an environment with a very large number of client devices that have very intermittent connectivity, have battery life concerns, are infrequently accessed via SSH (only a very small number at one time), and for which the economics of frequently reestablishing and maintaining a persistent open socket from each agent to the shellhub server doesn't make sense. These devices are on a network with an efficient but low-bandwidth/high latency notification/push channel (through HTTP polling, SMS notification or similar). It would be nice to have a configurable feature in shellhub whereby when an SSH client attempts to connect to an agent that does not have an active agent connection, a configured subprocess command could be invoked to initiate such an out-of-band push notification to the device, followed by waiting for a configurable timeout for the device agent to establish a connection before timing out the SSH connection attempt.

On the server-side, webhooks could be used for integration with 3rd-party applications

**Comment by gustavosbarreto** [comment]
![download (72)](https://user-images.githubusercontent.com/86747/108251404-19cd7500-7136-11eb-9732-1da2698b910e.png)

**Comment by otavio** [comment]
Is there any reason to not leave the agent running? I'd like to understand the use case.

**Comment by gustavosbarreto** [comment]
> Is there any reason to not leave the agent running? I'd like to understand the use case.

I want to keep the agent as generic as possible with no vendor-specific implementation required but easily pluggable

**Comment by gustavosbarreto** [comment]
> I want to keep the agent as generic as possible with no vendor-specific implementation required but easily pluggable

I want to keep the agent (AND server too) as generic as possible with no vendor-specific implementation required but easily pluggable.

That's why I proposed the webhook-based solution

**Comment by otavio** [comment]
Sure @gustavosbarreto; I understand this. I am wondering about @sammck use case.

**Comment by gustavosbarreto** [comment]
> Sure @gustavosbarreto; I understand this. I am wondering about @sammck use case.

I think it’s to save bandwidth on the device, since while the agent is running it is connected to the server.

**Comment by sammck** [comment]
> Is there any reason to not leave the agent running? I'd like to understand the use case.

I don’t object to keeping the agent running, but it is important that the socket to the server is closed when the agent is idle. If the agent does not shut down, I would need a way to signal the running agent to reestablish the connection to the server. It seemed less invasive to your project to just let it shut down and let me decide when to restart it...

**Comment by otavio** [comment]
So you are aiming to reduce data use, @sammck? or the problem is the connection which is kept open?

**Comment by sammck** [comment]
> So you are aiming to reduce data use, @sammck? or the problem is the connection which is kept open?

On the server side, I am aiming to be able to economically scale up to hundreds of thousands of client devices, with only a very small number ever having any need for a shellhub connection--i.e., less than 10 at any time. I do not want to deal with hundreds of thousands of open TCP sockets on the server that are never used, and the repeated connection/authentication processing as clients needlessly connect and disconnect for sessions that are never used. This argument also applies for the firewall/load-balancer which has state to maintain for each websocket/tcp connection.

On the client side, I want to avoid bandwidth and radio/cpu power concerns on small embedded devices, associated with repeatedly setting up and tearing down an authenticated connection to the server that is never used. This is particularly a problem in environments where network connectivity is very intermittent -- network availability may come and go many times in a day. The general approach with these devices is that there is a single very cheap way to wake them up and make them "phone home", and all server-initiated contact with the devices should build on that mechanism.

There are also some security concerns from potential customers associated with having a persistent general-purpose tunnel open to all devices at all times; they would rather see the tunnel opened as an exception rather than a rule, with network monitoring/firewalls able to detect anomalies and impose constraints.  This is more of a mindset issue than a technical argument but it's a real concern.

**Comment by otavio** [comment]
@sammck, thanks a lot for explaining your intended use case; it was precious.

@gustavosbarreto and I spoke about this, and the webhook proposal seems to be the best building block to allow this level of automation and flexibility.

@sammck, are you able to implement this and contribute the feature? How do you envision this?

**Comment by sammck** [comment]
I have limited experience with go but I'll see what I can do and submit a pull request. I agree that a webhook is a good approach (it would be nice if the configured webhook url supported connecting to a unix domain socket somehow). I think it will also be necessary to have server-side configuration for timeout after webhook invocation, waiting for the agent to connect.

For now i will skip doing anything on the agent side and just rely on an out of band way to shut the agent down and start it up again.

Thanks much for the receptive discussion...

**Comment by otavio** [comment]
Initially, we ought to design the desired payloads, which would be the starting point.

@gustavosbarreto, can you share your thoughts on this?

**Comment by sammck** [comment]
If we're designing payloads, it would be nice to include the originating IP address, any identifying client/auth fingerprint information, and the registered device being targeted for connection.

Ideally the webhook could fail the request due to some out-of-band policy decision, in which case the server would just fail the connection attempt.

**Comment by gustavosbarreto** [comment]
First draft:

# Payload Headers

The payload sent by a webhook has the following headers:

| Header | Description |
|--|--|
| X-SHELLHUB-WEBHOOK-ID | A unique ID assigned by ShellHub that identifies the delivered webhook payload |
| X-SHELLHUB-WEBHOOK-SIGNATURE | A signature created using the signature key |

# Payload Body

The body of a webhook payload is a JSON object that describes the event that has been triggered.

| Field | Description |
|--|--|
| type | Event type |
| event | An object containing the event payload |

## Event types

The following event types are available:

| Name | Description |
|--|--|
| incoming_connection | A new connection was made to the SSH Server |

## Event Payloads

Each webhook event payload also contains properties unique to the event. You can find the unique properties in the following individual event type sections.

### incoming_connection

| Field | Description |
|--|--|
| hostname | Device hostname |
| namespace | Device namespace |

**Comment by gustavosbarreto** [comment]
> Ideally the webhook could fail the request due to some out-of-band policy decision, in which case the server would just fail the connection attempt.

To acknowledge receipt of an event, the endpoint must return a `2xx` HTTP status code.
