### ISSUE TITLE
agent on OpenSUSE records sessions to utmp and wtmp incorrectly 

### ISSUE THREAD

**Issue by sixhills** [shellhub-io/shellhub#765]
When running on OpenSUSE 15.2 Leap, the agent handles the utmp and wtmp files incorrectly and reports "database size invalid".

utmp.go incorrectly assumes that the size of the Tv field in the Utmpx struct is the same as the size of unix.Timeval.  The Tv.Sec and Tv.Usec elements within the Utmpx struct are always 32-bit fields but the corresponding elements within unix.Timeval may be either 32 bits or 64 bits.  utmp records are written incorrectly on systems that use 64-bit values for time.

The proposed fix is to change the Tv field in the Utmpx struct from "unix.Timeval" to "Timeval" and to define Timeval as:

```
type TimeVal struct {
        Sec int32
        Usec int32
}
```
This ensures that the time values in the Utmpx record are always written as 32-bit values.

**Comment by otavio** [comment]
Have you checked if this works in both cases? If so, please prepare a PR fixing this.

**Comment by sixhills** [comment]
Yes, it works in both cases. I'll do some more testing then prepare a PR.

**Comment by sixhills** [comment]
I've tested the Shellhub agent with this fix on the following systems:

```
Name                          Arch   utmp record size    utmp fix
                                         (bytes)          works?

Debian 10.8.0 32-bit          i686         384             Yes
Debian 10.8.0 64-bit          x86_64       384             Yes
Fedora 33 64-bit              x86_64       384             Yes
OpenSUSE Leap 15.2 64-bit     x86_64       384             Yes
R-Pi OS Latest 32-bit         armv71       384             Yes
R-Pi OS Latest 64-bit         aarch64      400             No
Ubuntu 20.4 x86 LTS 64-bit    x86_64       384             Yes
Ubuntu 20.10 x86 64-bit       x86_64       384             Yes
Ubuntu 20.10 R-Pi 32-bit      armv71       384             Yes
Ubuntu 20.10 R-Pi 64-bit      aarch64      400             No
```

The standard size of a utmp record is 384 bytes and almost all systems (both 32-bit and 64-bit) use 384-byte records.  The code (with this fix) works fine on all these systems.

The two systems where the code doesn't work correctly are both 64-bit Raspberry Pi systems.  These both implement a utmp record using 400 bytes.  The extra 16 bytes are accounted for by the size of ut_session, ut_tv.tv_sec and ut_tv.tv_usec fields.  On a normal system, these are all 32 bits.  But on these two rogue systems, these fields are all 64 bits.  I think this may be a mistake in building them because utmp.h on all systems states "The ut_session and ut_tv fields must be the same size when compiled 32- and 64-bit.  This allows data files and shared memory to be shared between 32- and 64-bit applications."  I'll ask the developers of these two systems for their view.  It's particularly odd that Ubuntu 20.10 64-bit uses 384-byte records on x86 but 400-byte records on arm.

The question is what to do about this issue within the agent code. It would be inelegant to have to deal with both 384 and 400-byte records, especially if the use of 400-byte records is found to be a build error.  A possibility is to include a sanity check in the code: only write to utmp/wtmp if the file is a multiple of 384; if not, simply don't record login sessions.

What do you think we should do?

**Comment by otavio** [comment]
This is only the case when `__WORDSIZE_TIME64_COMPAT32` is enabled (https://github.com/bminor/glibc/blob/master/bits/utmp.h#L75-L85 and https://github.com/bminor/glibc/blob/be9b0b9a012780a403a266c90878efffb9a5f3ca/bits/wordsize.h#L23-L27).

For `aarch64`, this is not set (https://github.com/bminor/glibc/blob/21c3f4b5368686ade28d90d8c7d79c4c95c72c1b/sysdeps/aarch64/bits/wordsize.h#L28), so we need to add support to check this in build time and use the proper size of the types in this case.

**Comment by sixhills** [comment]
Thanks - I'm curious about why `__WORDSIZE_TIME64_COMPAT32` isn't set in aarch64 but that explains why this affects only those two systems. I'll test it again using conditional compilation.

**Comment by otavio** [comment]
Looking at the `git blame` didn't raise any information, so I don't know why those are different.

**Comment by sixhills** [comment]
Is the correct Golang technique to duplicate utmp.go, change the struct definition in the alternate version and use `// +build arm64` and `// +build !arm64` tags?

**Comment by otavio** [comment]
I believe this is the only way of doing it, without involving `cgo`.

**Comment by sixhills** [comment]
Is there a convention for the names of the utmp.go files?  utmp_arm64.go seems logical but I'm not sure what to call the utmp_everything_else.go file.

**Comment by otavio** [comment]
What about `utmp_time32.go` and `utmp_time64.go`?

**Comment by sixhills** [comment]
That sound good.Thanks.

**Comment by sixhills** [comment]
I've found that Gentoo 64-bit aarch64 for Raspberry Pi also uses 400 byte utmp records with 64-bit time fields.  So it's not just Debian derived aarch64 (Ubuntu 64-bit and Raspberry Pi 64-bit OS) that does this.  I'm assuming that all aarch64 are the same.

**Comment by otavio** [comment]
Yes @sixhills. As I mentioned this is defined inside the glibc source. For aarch64, the `__WORDSIZE_TIME64_COMPAT32` is not set (https://github.com/bminor/glibc/blob/21c3f4b5368686ade28d90d8c7d79c4c95c72c1b/sysdeps/aarch64/bits/wordsize.h#L28), so we need to add support to check this in build time and use the proper size of the types in this case.
