### ISSUE TITLE
HTTPS without a valid certificate (server v0.6.0)

### ISSUE THREAD

**Issue by leoniloris** [shellhub-io/shellhub#821]
Hello!
I have a shellhub v0.6.0 running on a cloud server (EC2, Aws), with the required ports open for https and I have  the following configuration on my `.env.override`:

```
SHELLHUB_SSH_PORT=8888 # I need this
SHELLHUB_AUTO_SSL=true
SHELLHUB_DOMAIN=valid-public-domain
SHELLHUB_REDIRECT_TO_HTTPS=true
```

But I can't connect via secure http.

following are my running containers:
```
$ ./bin/docker-compose ps
       Name                     Command                  State                        Ports
-------------------------------------------------------------------------------------------------------------
shellhub_api_1       /bin/sh -c /api                  Up
shellhub_autossl_1   /entrypoint.sh /usr/local/ ...   Up             0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
shellhub_gateway_1   /entrypoint.sh /usr/local/ ...   Up (healthy)
shellhub_mongo_1     docker-entrypoint.sh mongod      Restarting
shellhub_ssh_1       /bin/sh -c /ssh                  Up             0.0.0.0:8888->2222/tcp
shellhub_ui_1        /scripts/entrypoint.sh           Up             80/tcp
```
docker composer v 1.28.5
docker version 19.03.13-ce

Did I do something wrong? What is missing.
Thanks a lot!

![image](https://user-images.githubusercontent.com/22769167/112040684-448b5e80-8b24-11eb-9052-3210fbb150db.png)

**Comment by gustavosbarreto** [comment]
> SHELLHUB_DOMAIN=valid-public-domain

@leoniloris did you set `SHELLHUB_DOMAIN` with a valid public doamin pointed to your EC2 instance?

**Comment by leoniloris** [comment]
Yep.

**Comment by leoniloris** [comment]
> > SHELLHUB_DOMAIN=valid-public-domain
> 
> @leoniloris did you set `SHELLHUB_DOMAIN` with a valid public domain pointed to your EC2 instance?

Yep.

**Comment by gustavosbarreto** [comment]
@leoniloris you are getting this error because EC2-generated domain name happens to be on the blacklist of Let's Encrypt

See: https://community.letsencrypt.org/t/policy-forbids-issuing-for-name-on-amazon-ec2-domain/12692/2

**Comment by otavio** [comment]
It'd be good to have this as a FAQ entry as this should become common as more people start to deploy their instances.

If you agree, we could assign this to @Domarys so she can look at it.

**Comment by leoniloris** [comment]
Alrigh, I'll close this issue.
