### ISSUE TITLE
Registration on https://cloud.shellhub.io/sign-up does not work

### ISSUE THREAD

**Issue by ThEWiZ76** [shellhub-io/shellhub#843]
I tried registering on https://cloud.shellhub.io/sign-up
No matter what name I use, I always get "This name is already taken"

**Comment by gustavosbarreto** [comment]
@ThEWiZ76 our cloud servers were experiencing some instability. Can you please test it again?

**Comment by ThEWiZ76** [comment]
Just gave it a try, still no joy. No matter what name I choose, it is already taken

**Comment by noreng-jg** [comment]
Hello @ThEWiZ76
could you inform the name of the username you inserted?
The 'username' field must be a alphanumeric:
For example 'myusername333', without spaces or punctuation

**Comment by noreng-jg** [comment]
Thanks for reporting @ThEWiZ76 , I found out that the 400 response status was showing to the wrong
form field, name instead of username.

**Comment by ThEWiZ76** [comment]
Great! This worked, I had an _ in my username. Thanks for the help!
