### ISSUE TITLE
Add a message to advice that namespace name already in use

### ISSUE THREAD

**Issue by Domarys** [shellhub-io/shellhub#880]
In the namespace creation, when the namespace name is already used, an error message appears but does not inform the error reason.

![error3](https://user-images.githubusercontent.com/13737233/115452408-c4284e00-a1f4-11eb-906e-e49b9a82a8d0.png)

**Comment by leonardojoao** [comment]
@Domarys did you try to create a namespace with another name?
When you create a namespace, but the name already exists, error 500 will occur in the request.

**Comment by Domarys** [comment]
Yes, with the other name everything is ok. But when the name is already in use for another namespace, the message above appears but does not say anything about the error to the user.

**Comment by leonardojoao** [comment]
@gustavosbarreto In this case, what are we going to do?
