### ISSUE TITLE
Question about Helm Chart Availability

### ISSUE THREAD

**Issue by bpoulse** [shellhub-io/shellhub#973]
This is not a bug report. I noticed in the list of todo's for v0.7.0 there was a mention of a helm chart. It does not look like it, but is there a shellhub helm chart available for use at all?

**Comment by otavio** [comment]
Hello; we do use a Helm chart in our SaaS and enterprise versions. Honestly, it just makes sense if you are using a huge number of devices. How many devices are you using?

**Comment by bpoulse** [comment]
Not many, but we keep shellhub on a separate server, where it would be nice to integrate it into a cluster we have for general purpose chart deployments.

**Comment by otavio** [comment]
@bpoulse I ended not getting back to you about this question. So we will maintain the Helm Chart as an Enterprise version offering for the time being. Apologies for any inconvenience.
