### ISSUE TITLE
[Agent] Doesn't seem to work with Debian Bullseye

### ISSUE THREAD

**Issue by cusspvz** [shellhub-io/shellhub#989]
I'm trying to debug the reason why I'm getting this error when I attempt to either run the `curl` provided script, or actually execute the agent container manually:

```
WARN[0000] Error: No such container:
```

If i build the agent from the source code I'm able to connect and use it.

After reading through the code, I believe it could be related with the fact I'm using docker v20 and the selfupdate piece in [here](https://github.com/shellhub-io/shellhub/blob/596e0ee52e8abe5b9cedcb0b1f676f834681f6d8/pkg/dockerutils/utils.go#L10)

**Comment by otavio** [comment]
What distro version are you using? We found some issues related to the new cgroups versions, in recent Linux kernel and systemd  which might explain what you are facing.

**Comment by gustavosbarreto** [comment]
Maybe fixed in https://github.com/shellhub-io/shellhub/commit/6e152ee38046d180f8c1978f0704d1213d4578b5

**Comment by otavio** [comment]
@cusspvz can you validate the master branch? We believe it should work just fine.

**Comment by cusspvz** [comment]
I've tested with **Debian Buster** and it worked just fine. So probably @otavio 's right. I don't have a way to replicate it again because I ended up replacing the server's OS. Although, I believe you might be able to replicate it with a fresh Debian Buster installation.

**Comment by otavio** [comment]
I'll then close this as the fix is already part of the next release.
